### ISSUE TITLE
Scroll to Element on Page Load

### ISSUE THREAD

**Issue by joemcbride** [fisshy/react-scroll#10]
One thing I would like to do is be able to scroll to an `Element` on page load.  For instance, I'm currently using `react-router` to change the url when a user clicks on a nav element.  The user stays on the same page but the url changes.  `/mypage` to `/mypage/section1`.  That way the user can hand off that url to someone else and when the page loads it auto-scrolls to that section.

I think having some sort of service that tracks the registered elements would enable this scenario.

Some pseudo code.

```
class Page {
  componentDidMount() {
    let section = this.context.router.getParams();
    // scroll service knows about all elements on page
    myScrollService.scrollTo(section)
  }

  componentDidUnmount() {
    // let the service know to purge all its data
    myScrollService.unmount();
  }
}
```

**Comment by fisshy** [comment]
good point, but doesn't react-router repaint the view when you navigate to a new URL? 

Or are you keeping all the sections under /mypage and using "section1" as param?

This feature should be added, gotta figure out a nice way to integrate it with react-router.

**Comment by joemcbride** [comment]
All sections are under `/mypage` and `section1` is a param.  I have this currently working with react-router, just not the "scroll to section on page load" portion.

**Comment by joemcbride** [comment]
Here's what the route looks like.
```
<Route name='mypage' path='/mypage/?/:section?' handler={MyPage}/>
```

**Comment by deezahyn** [comment]
@fisshy so what's the final api here?  How do you scroll by id pragmatically?

**Comment by joemcbride** [comment]
@deezahyn This is how we are doing it.

```
import React from 'react';
import Row from 'react-bootstrap/lib/Row';
import Col from 'react-bootstrap/lib/Col';

import { scroller, scrollSpy } from 'react-scroll';

class ComponentsPage extends React.Component {

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    let params = this.context.router.getCurrentParams();
    if (params.section && params.section.length > 0) {
      scroller.scrollTo(params.section, false, 0, -65);
    }
  }

  componentWillUnmount() {
    scrollSpy.unmount();
    scroller.unmount();
  }

  render() {
    return (
      <Row>
        <Col md={10}>
          <div>Components here</div>
        </Col>
      </Row>
    );
  }
}

ComponentsPage.contextTypes = {
  router: React.PropTypes.func.isRequired
};

export default ComponentsPage;
```

**Comment by deezahyn** [comment]
what's the param section? is that a string? or DOM?  Say I can access the actual dom via refs. this.refs.myBox.  How would I go about scrolling to that parameter?

**Comment by joemcbride** [comment]
@deezahyn Have a look at the [example](https://github.com/fisshy/react-scroll/blob/master/examples/basic/app.js).  You use `<Element name='myLink'>` and `<Link to='myLink'>`.  The `Link` scrolls to the item defined by `Element` when it is clicked.  If you want to manually do it yourself, outside of the `Link` (such as on Page Load, which is what the issue is you are posting on), you can use the `scroller` as I posted above.  You still use `Element` to define the sections that can be scrolled to.  You don't work with DOM elements directly.

**Comment by joemcbride** [comment]
[This is how](https://github.com/fisshy/react-scroll/blob/master/modules/mixins/Helpers.js#L96) `Element` knows what to scroll to.

**Comment by deezahyn** [comment]
it says `target Element not found`

**Comment by joemcbride** [comment]
@deezahyn Please open a new issue and post the code you're having trouble with.
