### ISSUE TITLE
scrollTo doesn't works passing a object as second parameter

### ISSUE THREAD

**Issue by marciovicente** [fisshy/react-scroll#101]
`scroller.scrollTo` function doesn't works using an object as props:
```
    scroller.scrollTo(target, { offset: 100, smooth: true });
```
Looking around the compiled code I've checked the code, and the `scrollTo` method expect the these parameters: `(to, animate, duration, offset)`. So, when I tried to use the exactly match it's works fine:

```
    scroller.scrollTo(hashTarget, true, false, -120);
```
I'm using the 1.0.4 library version and have no idea where I could find the releases documentation.

Feel free to close this issue if this doesn't makes any sense, otherwise I think is necessary to update the documentation.

Best regards!

**Comment by fisshy** [comment]
Are you using "animate-scroll"?

**Comment by kiranps** [comment]
same here

var scroller = Scroll.scroller;

` 
    scroller.scrollTo('element1', {
      containerId: "scrollcontainer"
    })
`

I'm getting an error

`Uncaught Error: Container with ID scrollcontainer is not a positioned element`

**Comment by marciovicente** [comment]
@fisshy I'm using `scroller`..
```javascript
import { scroller } from 'react-scroll';
// [...]
scroller.scrollTo([...])
```

**Comment by fisshy** [comment]
Checkout the README

var Scroll = require('react-scroll');
var scroll = Scroll.animateScroll;
scroll.scrollTo(100, options);

I should probably make the API a bit more convenient, It can be confusing now.

**Comment by fisshy** [comment]
Looks like scrollTo('element') doesn't match scrollTo('px'). I might fix this later today.

**Comment by marciovicente** [comment]
Sorry, but I don't get it... There are two scrollTo, right? `animateScroll.scrollTo` and `scroller.scrollTo`. The first accept the unit in pixels and the second expect an element. 
Maybe my question is not clear.. my `hashTarget` variable is a `Element`..
```javascript
<Element name="myElement"> [...] </Element>

import { scroller } from 'react-scroll';
scroller.scrollTo('myElement', {... args});
```
 You might to use something like this in the future:
```javascript
scroller.scrollToElement('myElement', {});
srollAnimate.scrollTo(100, {});
```

**Comment by fisshy** [comment]
yes you are right and both should go under the "scrollAnimate" to not confused. 
One was meant as the public API and one was used internally but I guess you can use both outside as well.
