### ISSUE TITLE
offsetParent check causing problems in container scrolling

### ISSUE THREAD

**Issue by nathanielkornet** [fisshy/react-scroll#103]
https://github.com/fisshy/react-scroll/blob/master/modules/mixins/scroller.js#L65

`Container with ID ' + containerId + ' is not a positioned element`

So I'm running into an issue while trying to scroll a container (via `containerId` prop) to a specified `Element`. It's hitting the above linked error even thought the container specified is in fact a positioned element.

Here's what's happening:

I have a `containerElement` that I want to scroll which is a positioned element. I then have an `Element` nested fairly deep inside this container that I want to scroll to. When I try to scroll I hit the aforementioned error. This is happening because there is another positioned DOM element between the `containerElement` and the `Element` I am trying to scroll to. This causes the `offsetParent` of the `target` Element to be set to set to the intermediate element rather than the desired `containerElement`.

I understand why `offsetParent` is used here, but it prevents the use of other positioned elements between the desired container and the target element. If this is a limitation that can't be avoided then the error handling should probably be updated, because the error is misleading and incorrect.

@fisshy @poacher2k

**Comment by nathanielkornet** [comment]
```
<div id="container" style="position: absolute, overflow-y: 'scroll">
  <div id="intermediate" style="position: absolute">
    <Element name="myScrollToElement" />
  </div> 
</div>
```
```
scroller.scrollTo('myScrollToElement', {
  duration: 1500,
  delay: 100,
  smooth: true,
  containerId: 'container'
})
```

For clarification. This DOM pattern would cause the error to be thrown, even though the container is positioned.

**Comment by poacher2k** [comment]
Agreed! I'll look at this tomorrow!

Den søn. 10. jul. 2016, 20:11 skrev Joachim <notifications@github.com>:

**Comment by poacher2k** [comment]
I guess sometimes tomorrow comes later than planned.

It's no trouble to just change the error message to properly reflect what is the issue, ie. "The given `containerElement` is not the same as the `offsetParent` of the `element`". 

The ideal situation, though, would be to just magically scroll to the `element`. As far as I can tell, there's no really good way to do this, at least not without being overly "smart". I do not believe that we, as an example in the case where `div#intermediate` has many children but a fixed height, should implicitly scroll `div#intermediate` to reveal `myScrollToElement`, when the `intermediate` element is not the container specified with `containerId`.

This could instead be achieved by two calls to `scroller.scrollTo`, one with the `intermediate` element as target and `parent` as `containerId`, and one with the `myScrollToElement` as target and `intermediate` as `containerId`.

**Comment by rahulbandi** [comment]
I am just doing a drop down with  text box and image button which opens the div elements which contains nested div's....till now it's perfect...but i want to move the scroll bar to selected options...I only using pure JavaScript...can anyone plz suggest

**Comment by nathanielkornet** [comment]
@rpearce unfortunately the only solution i found was to remove positioning from the intermediate element, which forced me to refactor the css to achieve the same visual effect. I was able to find a suitable solution using `float` instead of absolute positioning.

**Comment by rpearce** [comment]
@nathanielkornet Gotcha. I went with calculating the exact location on the page of the element and just using `animateSroll.scrollTo` ¯\_(ツ)_/¯.

Thanks for sharing

**Comment by xSequential** [comment]
@nathanielkornet I cry inside whenever I am forced to use float :/

**Comment by aaronbeall** [comment]
I've run into the same problem. Similar to the OP I've got a container with `overflow-y` and an inner container that is absolutely positioned to create a locked column table layout. I don't need any intermediate scrolling I just need the outer container to scroll vertically to show an element in the inner container.... refactoring to use floats is going to be hard if not impossible because of the crazy CSS I have...

**Comment by aaronbeall** [comment]
I spoke too soon, of course I've been struggling with this for a few hours but it turned to be a matter of replacing a `position: absolute; left: X` with `margin-left: X` to shed the extra positioned container. Still, would be really helpful if `react-scroll` could handle this case, without any fancy intermediate scrolling, instead of throwing an error.
