### ISSUE TITLE
Active class is not set on initial render

### ISSUE THREAD

**Issue by markhaasjes** [fisshy/react-scroll#104]
In order to use the scroll spy (with a sidebar menu for example). The element which is inside the viewport on initial render doesn't have a active class.

This problem also occurs on the example of this repo: http://fisshy.github.io/react-scroll-example/basic/index.html

I saw a pull request for this issue, but were rejected for a different reason. I would love to see this working.

**Comment by markhaasjes** [comment]
Thanks @fisshy! Looking forward to it 👍

**Comment by HopeLyn** [comment]
+1

**Comment by fisshy** [comment]
Sorry but I haven't had the time yet, currently on vacation. I did try to fix it, but couldn't come up with something quick. Will try to solve it once I'm back home.

**Comment by mariotacke** [comment]
Hi fisshy, would love to see if you were able to find a solution yet!

**Comment by fisshy** [comment]
Hi @mariotacke, I'm back today and I will fix it before I go to sleep today :)

**Comment by fisshy** [comment]
I've now solved this, but you will have to call scrollSpy.update(); in your componentDidMount. 

Because links/elements are dynamic so there's no way to detect when all the elements has been rendered and linked. So the best way is to call scrollSpy.update() in your component that wraps your links/elements. 

It has been published in v1.1.0. I've also updated the README.

**Comment by mariotacke** [comment]
Excellent work. Thank you for this great lib!

**Comment by markhaasjes** [comment]
Thanks @fisshy this is really helpful!

**Comment by fisshy** [comment]
Glad you like it @markhaasjes  and @mariotacke !

**Comment by adamrabie** [comment]
this isn't working for me. I call it in the component which wraps the link function in the setState callback which renders the items. I've even tried an arbitrary but long enough timeout before calling update() and still do not get an initial active state. It only becomes active after a tiny scroll.

**Comment by mohaimenmahi** [comment]
My activeClass on Link is not working. I followed this link: 
https://scotch.io/tutorials/implementing-smooth-scrolling-in-react. 

What should I do? I already Added the scrollSpy.update() in componentDidMount() but nothing worked.

**Comment by Marius-Adam** [comment]
> My activeClass on Link is not working. I followed this link:
> https://scotch.io/tutorials/implementing-smooth-scrolling-in-react.
> 
> What should I do? I already Added the scrollSpy.update() in componentDidMount() but nothing worked.
Hello, 
Have you managed to solve this?

**Comment by Marius-Adam** [comment]
I also tried achieving this by adding scrollSpy.update() and did not work
