### ISSUE TITLE
React 15.2 causes console warnings component

### ISSUE THREAD

**Issue by alaindresse** [fisshy/react-scroll#105]
React 15.2 issues warnings when unknown attributes are assigned to Dom components (see [https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom](https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom)).

This brings issues with Link.js that passes all props to <a> : 

Warning: Unknown props `activeClass`, `spy`, `smooth`, `duration`, `isDynamic` on <a> tag.

**Comment by fisshy** [comment]
Are you using the lastest version of react-scroll?

**Comment by alaindresse** [comment]
You are right, I did not have the latest version (I had 1.0.17).
But then I have another issue: I use Helpers.Element, and not it no longer passes my props…

See my code below: the title prop in UnnamedSection is not maintained with the Element higher order component…

Shall I note this as another issue ?
var Scroll = require('react-scroll’);
…
var UnnamedSection = ({className, title, children})=>(
    <section className={cx("clearfix", className)}>
        <div className="section-body">
            {title && <h1>{title}</h1>}
            {children}
        </div>
    </section>
);

var NamedSection = Scroll.Helpers.Element(UnnamedSection);

Best regards,
Alain

**Comment by fisshy** [comment]
Yes, it's an issue. I will see if there is a away to pass any "naitive" property. Will look into it.

**Comment by fisshy** [comment]
You can now pass any native property, check out the newest version. v1.0.22
