### ISSUE TITLE
Cannot read property 'containerId' of undefined setContainer 

### ISSUE THREAD

**Issue by house9** [fisshy/react-scroll#106]
Version: 1.0.21

calling `scroll.scrollToBottom();` without any options will throw the following exception:

```
animate-scroll.js:129 Uncaught TypeError: 
  Cannot read property 'containerId' of undefined setContainer 
@ animate-scroll.js:129 scrollToBottom 
@ animate-scroll.js:172 (anonymous function) 
```

It looks like it might be related to the `setContainer` method added in this commit:

https://github.com/fisshy/react-scroll/commit/2f7c9daa7711c956f8fbd2a009668d9b4b240dac#diff-caeaa97173683450989d68dd0c4fdaf4R128

It looks like other places that pass around the options also default to an empty object. Is that something that should be happening in this case, too? Like `setContainer(options || {})`

Workaround: pass an empty options object when calling it from your application `scroll.scrollToBottom({});`

**Comment by fisshy** [comment]
Thanks, I've now solved it in the latest version v1.0.24.
