### ISSUE TITLE
Mixin/ScrollSpy incorrect punctuation causing build error

### ISSUE THREAD

**Issue by chrismllr** [fisshy/react-scroll#116]
`SyntaxError: Unexpected token punc «(», expected punc «:» [./~/react-scroll/lib/mixins/scroll-spy.js:32,0]`

looks like offender is
```
isMounted(scrollSpyContainer) {
  return this.scrollSpyContainers.indexOf(scrollSpyContainer) !== -1;
}
```

I will attempt to get a PR in soon

**Comment by fisshy** [comment]
ah!, thanks! :)

**Comment by chrismllr** [comment]
@fisshy Got one opened, PR #117

**Comment by mmmeff** [comment]
Woosh, this one took me a little bit to  figure out. Thanks for already fixing it, @chrismllr
