### ISSUE TITLE
Using with react-router

### ISSUE THREAD

**Issue by re6exp** [fisshy/react-scroll#12]
Is it possible to use react-scroll in conjunction with react-router?

**Comment by fisshy** [comment]
Yes It should be possible - havn't figured out what the best practice is yet.

**Comment by re6exp** [comment]
In different cases we can find different approachs to be best. So many cases are there. :)

We have mobile-first application. In some cases the site information can (or, should) be devided into parts separated by sense (product list and contacts form). I'd like to separate these parts by including them to different handlers (views). This is router-supported parts. But if one of the views contain similar but not the same elements (products) and user looks over them sequentially I'd like to use control set like react-scroll. At the same time it can be useful to represent these elements or groups of the elements in navigation too.
Concerning the example usecase, when I go back from contacts form to product list view, how do I properly arrive appropriate element or group specified by Scroll.Element?

My guess is scrolling and routing complement each other.

**Comment by davis** [comment]
+1

**Comment by mrlarssen** [comment]
+1

**Comment by rafaelderolez** [comment]
+1

**Comment by Noitidart** [comment]
Why was this closed? Was a solution shared?

(note to @1yzo)
