### ISSUE TITLE
Smooth scroll not working when switching to a different route and back again.

### ISSUE THREAD

**Issue by charliedavison** [fisshy/react-scroll#120]
I have an application where react router loads a wrapper component, which in turn contains a component with react-scroll elements and links. This appears to work perfectly, however when I switch routes and then come back suddenly smooth scrolling no longer works when clicking on the links despite the "begin" and "end" events both being fired, and seemingly the correct parameters being passed around when I step through everything up to the point of "RequestAnimationFrameHelper".

If I turn smooth scroll off, the scroll bar is moved to the correct place(obviously without the animation).

I have tried in several browsers and it doesn't seem to be a browser specific issue - has anyone run into anything similar?

**Comment by fisshy** [comment]
I have not tried react-scroll with react-router ( or any routing  type of routing ). Might be that we remove some listeners in componentWillUnmount. I will take a look at it and hopefully tonight.

**Comment by erinmeyers88** [comment]
I'm having the same issue here.  Very interested in a solution!

**Comment by erinmeyers88** [comment]
This solution worked for me: https://github.com/fisshy/react-scroll/pull/114
