### ISSUE TITLE
Way to Change Color When Not Active

### ISSUE THREAD

**Issue by dschinkel** [fisshy/react-scroll#123]
If an anchor is not rendered to the page I wanna change its color since in those cases the link will be inactive.  Is there a built-in property for that or do I need to code that ability in?

**Comment by fisshy** [comment]
There's no functonallity for this, you will have to create your own link element. 

`var Link = React.createClass({
  render: function () {
    return (
      <a>
        {this.props.children}
      </a>
    );
  }
});

module.exports = Helpers.Scroll(Link);`

**Comment by dschinkel** [comment]
cool thanks, I'll try it out.
