### ISSUE TITLE
use scrollTo() to scroll to anther file

### ISSUE THREAD

**Issue by SnapluDJ** [fisshy/react-scroll#135]
Hi fisshy,

I want to use scroller.ScrollTo to scroll to another file, but failed

here is what I have done:

I put `<Element name="myScrollToElement"></Element>` in file A,

then I put 
`scroller.scrollTo('myScrollToElement', {
  duration: 1500,
  delay: 100,
  smooth: true,
})` in file B,

I don't know how to write the route to file A along with 'myScrollToELement' in a right way in scroller.scrollTo() function, 
could you please give me some hint?

Thanks!

**Comment by fisshy** [comment]
Hi,

I'm not really sure what you mean with another file?

**Comment by SnapluDJ** [comment]
Never mind fisshy, I have figured it out.

**Comment by fisshy** [comment]
Good to hear!

**Comment by GainorB** [comment]
How did you do this? @SnapluDJ
