### ISSUE TITLE
Doesn't seem to be working in IE10

### ISSUE THREAD

**Issue by kosanna** [fisshy/react-scroll#145]
Hey, we've implemented this awesome scroll library on our project, works perfect across all browser except IE10 for some reason (did not test below, do not support)

**Comment by DJ-Icebear** [comment]
I had the same issue as well. Seems like it breaks on Line 32 in /lib/mixins/scroll-spy.js
I fixed it by replacing the line:
`isMounted(scrollSpyContainer) {`
with:
`isMounted: function (scrollSpyContainer) {`

**Comment by fisshy** [comment]
isMounted issue should be fixed now.
