### ISSUE TITLE
Remove React as direct dependency

### ISSUE THREAD

**Issue by maxdeviant** [fisshy/react-scroll#146]
Could we make React and ReactDOM peer dependencies instead of direct dependencies in the `package.json`?

This is the general practice for most React libraries, and prevents the issues that occur when you have two different versions of React in the same project.

**Comment by dlmanning** [comment]
Seconded. What's up with this?

**Comment by fisshy** [comment]
Feel free to make a PR 👍

**Comment by dlmanning** [comment]
@fisshy : done: https://github.com/fisshy/react-scroll/pull/182

I've made it a devDependency. It could also reasonably be made a peerDependency. If you'd rather that I'll update the PR.

**Comment by maxdeviant** [comment]
@dlmanning I think peerDependency is the more common approach. That way it will actually warn if you install it without having React installed

**Comment by dlmanning** [comment]
@maxdeviant : updated PR to add as peer deps too.

Personally I find those warnings to be more a nuisance than helpful, but I think you're correct that this is the more common practice.
