### ISSUE TITLE
Unmounting scrollspy causes error

### ISSUE THREAD

**Issue by gingerich** [fisshy/react-scroll#152]
```
Uncaught TypeError: Cannot read property 'splice' of undefined

unmount	@	scroll-spy.js:82
componentWillUnmount	@	Helpers.js:169
(anonymous function)	@	ReactCompositeComponent.js:408
measureLifeCyclePerf	@	ReactCompositeComponent.js:74
unmountComponent	@	ReactCompositeComponent.js:407
unmountComponent	@	ReactReconciler.js:80
unmountChildren	@	ReactChildReconciler.js:147
unmountChildren	@	ReactMultiChild.js:375
...
```

Looks like this can happen when scrollspy is unmounted before any spyHandlers are added.
Introduced by b8bbbd5.

Let me know if you need more info to repro.

**Comment by fisshy** [comment]
Thanks for finding it,
Let me check it out later today and I will publish a fix for it.

**Comment by rcmontoy** [comment]
If all you need is simple scrollTo, I am currently using the following as a workaround

```javascript
import {scroller, Element} from 'react-scroll'

scroller.scrollTo('elementName', {
  duration: 500,
  smooth: true
});

<Element name="elementName"></Element>
```

**Comment by fisshy** [comment]
I've now solved this issue in v1.4.2

**Comment by screamsyk** [comment]
this issue appear again in 1.8.6

**Comment by screamsyk** [comment]
![image](https://user-images.githubusercontent.com/25660357/161732747-8289a7d9-6f94-45f8-a2f1-d99388248fca.png)
I found the reason that `indexOf` return -1，so `splice` still work
