### ISSUE TITLE
Scrolling gets cancelled if a keydown event  happens during scroll

### ISSUE THREAD

**Issue by npopov-divx** [fisshy/react-scroll#153]
Hi, i am using this library to implement smooth scrolling from item to item in a arrow key driven vertical list.
In my code, on key down event i calculate if the next item in the list is partially visible or hidden, then use Scroll.animateScroll.scrollTo(pos, {duration: 300, smooth: true});

It works fine for single key presses, but any keypress during scroll animation phase will cancel the scrolling and "end" callback never gets called.
Is there any way to get around this problem?

**Comment by fisshy** [comment]
Hi, keydown will cancel the scroll right now.

You could add a property named "ignoreCancelEvents" or something like that

https://github.com/fisshy/react-scroll/blob/master/modules/mixins/cancel-events.js

and somehow override this

https://github.com/fisshy/react-scroll/blob/master/modules/mixins/animate-scroll.js#L22

Or you could just fork the code and remove the events yourself and use your version of it :)

**Comment by npopov-divx** [comment]
Gotcha, thank  you!
