### ISSUE TITLE
<a> cannot appear as descendant of <a>. React-Bootstrap error.

### ISSUE THREAD

**Issue by BartoszBaczek** [fisshy/react-scroll#154]
Hello, I am trying to use react-scroll with navbar in react-bootstrap.

Unfortunatelly I am getting this warning:

> Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. See NavigationBar > NavItem > SafeAnchor > a > ... > Constructor > Constructor > a.

Code which triggers this warning:

```
<Navbar>
  <Nav pullRight>
    <NavItem><Link activeClass="active" to="section-1" spy={true} smooth={true} duration={500}>Stuff</Link></NavItem>
  </Nav>
</Navbar>
```

Is there some workaround for this issue?

EDIT:
Just to be clear - scrolling itself works fine. I am only getting a warning.

**Comment by cmunson** [comment]
If you add a componentClass to NavItem and set it anything but a if will remove the error. Unfortunately this also messes up styling but that could be fixed in CSS.

`<NavItem key={ index } componentClass="span">
     <Link activeClass="active" to={ url } spy={true} smooth={true} offset={0} duration={500}>{title }</Link>
</NavItem>);`

**Comment by fisshy** [comment]
You could create your own "Link/a" element and it doesn't have to be an a tag. 
```
var React   = require('react');
var Scroll  = require('react-scroll');
var Helpers = Scroll.Helpers;

module.exports = Helpers.Element(Element);

var Link = React.createClass({
  render: function () {
    return (
      <a {...this.props}>
        {this.props.children}
      </a>
    );
  }
});

module.exports = Helpers.Scroll(Link);
```
