### ISSUE TITLE
Use semver versioning scheme

### ISSUE THREAD

**Issue by ruscoder** [fisshy/react-scroll#155]
http://semver.org

You removed `DirectLink` component in v.1.2.0 -> v1.3.0. It was breaking change.

**Comment by fisshy** [comment]
Not really, DirectLink just added duplication of code. Minor for me :)

**Comment by ruscoder** [comment]
DirectLink was provided in previous versions <=1.2 and some developers used it. 
After `npm install` new minor version broke existing code which was using DirectLink component.
According to semver, you should add deprecation warning for it instead of deleting.

But anyway, thanks for the package, @fisshy!
