### ISSUE TITLE
Scrollable within a div?

### ISSUE THREAD

**Issue by JaeHunRo** [fisshy/react-scroll#17]
Is it possible to configure scroll in order to scroll through a selected element (such as a div with overflow:scroll styling) rather than the window? I'm trying to customize the components to do so, but I might be missing an obvious functionality. Thanks

**Comment by fisshy** [comment]
Not sure it's possible in the current version.

https://github.com/fisshy/react-scroll/blob/master/modules/mixins/animate-scroll.js

Looking at line 71 - It could be possible to target an element and scroll that element I believe instead of the Window.

**Comment by JaeHunRo** [comment]
Ok, I'll try to modify it to work with divs or any other type of component. Thank you!

**Comment by JaeHunRo** [comment]
Hi, so I modified the files a bit and ended up editing them so that automated scrolling within a div was an option by using Element props! I'm working still on cleaning it up though

**Comment by fisshy** [comment]
Hi! Great job, sounds like a good to have feature :)

**Comment by JaeHunRo** [comment]
Sweet could I send you a pull request with the changes?

**Comment by fisshy** [comment]
Of course - but I will have to look into the code and test it first :)

**Comment by fisshy** [comment]
It's now possible to scroll within a div. Checkout v1.0.19.
