### ISSUE TITLE
Android Chrome Version 54.0.2840.85 issue

### ISSUE THREAD

**Issue by Phaze1D** [fisshy/react-scroll#175]
Not sure if this is just me but it doesnt seem to work with Android Chrome Version 54.0.2840.85
Am just using the basic code
`Scroll.animateScroll.scrollTo(event.target.closest('.tree').offsetTop, {duration: 400, smooth: true});`

**Comment by fisshy** [comment]
Do you get any error? Or nothing happens?

**Comment by Phaze1D** [comment]
Seems to be working now may have been my fault
