### ISSUE TITLE
not scrolling on first click

### ISSUE THREAD

**Issue by Cod-ey** [fisshy/react-scroll#179]
On first click, after the page loads in, the scroll action does not happen; but every subsequent click it works fine.
Any idea what may be causing this?

**Comment by fisshy** [comment]
Is it the same here as well? 

http://fisshy.github.io/react-scroll-example/basic/index.html

What browser?

**Comment by Cod-ey** [comment]
I get the behavior on both Firebox Developer and Chrome Canary.
That sample page works fine for me.

Not sure if it's a source of the problem, but I have multiple source buttons with the same value for the "to" attribute. So about 5 buttons pointing to the same target <Element>
 <Element name="myScrollToElement"></Element>

            <ButtonScroll
               to="myScrollToElement" spy={false} smooth={true} duration={500}
            >
              {button.name}
            </ButtonScroll>

Also I get the same behavior whether I use the default <Link> or my custom Scroll.Helpers button component.

**Comment by Cod-ey** [comment]
ok, I fixed it.
The <Element> was in a react component that hadn't rendered yet.
so I moved it to the parent component of that one, which was rendered on page load.

**Comment by fisshy** [comment]
Good that you solved it on yourself! :)
