### ISSUE TITLE
React@15.4.0 Warning

### ISSUE THREAD

**Issue by dicklwm** [fisshy/react-scroll#195]
#### Environment

- react-scroll version 1.4.8
- Nodejs and Npm version  6.10.0    3.10.10
- Operating environment (e.g. OS name) and its version:  Windows10，Chrome57.0.2987.110 (64-bit)

#### What happen?
When My ComponentDidMount , the console is warning , like this
```
Warning: Accessing PropTypes via the main React package is deprecated.
Use the prop-types package from npm instead.

Warning: A Component: React.createClass is deprecated and will be removed in version 16. 
Use plain JavaScript classes instead.
If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

```
![image](https://cloud.githubusercontent.com/assets/19289258/24891300/7a22b216-1ea7-11e7-85ce-3a76c1e60fa2.png)

#### What do you expected?
- **No Warning!** 
- I think you can use ES6 to refactor the component

**Comment by fisshy** [comment]
Thanks for the feedback, should be solved using their npm packages. 

Expect a fix this week or make a PR if you wan't :)
