### ISSUE TITLE
Feature: horizontal scrolling

### ISSUE THREAD

**Issue by alexdemartos** [fisshy/react-scroll#199]
Hi,

first of all, thank you all for the nice work. I'd like to ask: is horizontal scrolling in mind? Would it be hard to implement?

Thank you

**Comment by fisshy** [comment]
Hi,

Thank you!

I did have it in mind, but currently not on the schedule. 

I'm not sure if there's an API for it, but you could make a workaround and rotate the divs with css I believe.

**Comment by cdimitroulas** [comment]
this would be a useful feature!

**Comment by yarnball** [comment]
Is there any update on horizontal scroll? I want a smooth-scrolling/sort of spring animation for a horizontal list.

I attempted it here using `react-scroll` with no success:
https://codesandbox.io/s/km70l420pv

Any possibility of this working?

**Comment by fisshy** [comment]
Currently no support to do a horizontal scroll, I welcome any PR solving it! :)

**Comment by ArpiJakab** [comment]
Just a friendly note, please consider documenting the lack of horizontal scroll support in the README.

**Comment by Hassan0Rehman** [comment]
Glad to know its not supported. I was thinking i am not doing it properly :). Anyone has a good tested alternative for horizontal scrolling with good api ?

**Comment by yoiang** [comment]
Horizontal scrolling was just added in #429
