### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by colindresj** [fisshy/react-scroll#2]
Using version 36.0.1

**Comment by fisshy** [comment]
You have to give me more then that :) Preferably a Pull request :)

**Comment by colindresj** [comment]
Haha, you got it @fisshy! I'll submit a PR soon

**Comment by colindresj** [comment]
@fisshy Did you get a chance to republish this?

**Comment by fisshy** [comment]
I did it yesterday

**Comment by colindresj** [comment]
Awesome thanks for the responsiveness!
