### ISSUE TITLE
scroll to working wrong when refresh page

### ISSUE THREAD

**Issue by hoangtranuit** [fisshy/react-scroll#200]
Here is my code  

```
componentDidMount() {
    scroller.scrollTo('login', {
      duration: 500,
      delay: 200,
      smooth: true,
      spy: true,
      offset: -20
    })
  }

```
`  <Element class="login" name="login">`
Browser: Chrome

**Comment by lyudad** [comment]
Have same problem? How did you resolve it?

**Comment by hoangtranuit** [comment]
it's working when putting inside a setTimeout function.
but this is not a good solution.
hope this help.

**Comment by lyudad** [comment]
https://github.com/fisshy/react-scroll/issues/250
not work for me
