### ISSUE TITLE
React.createClass is deprecated

### ISSUE THREAD

**Issue by voold** [fisshy/react-scroll#201]
Can you fix that?

```React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead.```

Best!

**Comment by fisshy** [comment]
Yes, merging a fix today.

**Comment by fisshy** [comment]
Fixed in v1.5.0

**Comment by voold** [comment]
Thanks :)

2017-04-15 14:27 GMT+02:00 Joachim <notifications@github.com>:
