### ISSUE TITLE
Throwing Uglify Errors

### ISSUE THREAD

**Issue by jjmasse** [fisshy/react-scroll#202]
Pardon me, but the use of this token is creating build errors with Uglify.
`Webpack ^1.13.1`
`SyntaxError: Unexpected token: name (_) [./~/react-scroll/lib/mixins/Helpers.js:36,0]`

**Comment by Zerim** [comment]
Seeing the same issue. Don't think the '_' is the issue. The problem is that this module now using the ES6 class syntax in it's built output. Uglify can't parse ES6 code. The built output (as should that of most node_modules) should be ES5.

**Comment by gilLionKing** [comment]
i'm running into the same issue suddenly. a fix would be very helpful

**Comment by fisshy** [comment]
A fix would be to downgrade to 1.4.8.

**Comment by jjmasse** [comment]
Thanks, @fisshy I had downgraded to keep working along.  Seems that the pre 1.5.0 is ES5 as uglify is compatible with.  Perhaps we can solve this with some build configuration.  If I get a little time I wouldn't mind helping out.

**Comment by joeduncan** [comment]
https://github.com/joeduncan/react-scroll/commit/b7dbdda929fd1fbdc065761c5202366bd1ad8722 fixes issue for the moment, basically transpiling the files before publishing probably isn't a bad idea 😉

**Comment by joeduncan** [comment]
@fisshy do you want me to PR this?

**Comment by fisshy** [comment]
yes sure @joeduncan seems to be solving our issue so 👍
