### ISSUE TITLE
Webpack UglifyJsPlugin issue with react-scroll v1.5.0

### ISSUE THREAD

**Issue by NikIvan** [fisshy/react-scroll#207]
Hey, guys!

I was in process of migration project to webpack 2 yesterday and after removing `node_modules` tried to `npm install` and got `1.5.0` version of `react-scroll`

This what I got while trying to build my project: 
`ERROR in scripts/bundle.82220088b3fb11cac6e1.js from UglifyJs
Unexpected token: name (_) [./~/react-scroll/lib/mixins/Helpers.js:36,0]`

One of the solution was to include `react-scroll/lib/` to babel-loader source directories.

```javascript
test: /\.jsx?$/,
include: [ 
  path.resolve(__dirname, 'src'),
  path.resolve(__dirname, 'node_modules/react-scroll/lib'),
],
```

I know already that this issue is fixed in `1.5.2` and the reason was that `react-scroll` source wasn't passed through babel and `uglify` can't minify ES6 code for the moment.

Just want to notify anyone who, probably, will stuck with this issue.

Thanks for the nice lib and for the fast issue solving.
Have a nice day!

**Comment by NikIvan** [comment]
I think the issue can be closed any moment

**Comment by fisshy** [comment]
Thank you, glad it solved your issue!
