### ISSUE TITLE
scrollTo cannot target element

### ISSUE THREAD

**Issue by MattyChance** [fisshy/react-scroll#215]
Hello,

I am pretty new to this so excuse me for not being able to make this work.

I added Element in my react component like this:
```
<div>
    <Element className='position-name'>
	<Field
		name="name"
		component={InputField}
		type="text"
	        label={<label>Nom du réseau</label>}
		required={true}/>
    </Element>
    <Element className='position-address'>
	<Address />
    </Element>
</div>

//in another file I have my functions which map a form's invalid fields errors into an array and I try to use react-scroll to scroll to the first error

import { scroller } from 'react-scroll';

export function scrollToFirstError(errors) {
  const errorFields = getErrorFieldNames(errors);
  console.log('errorFields: ', errorFields)

  for (let i = 0; i < errorFields.length; i++) {
    const fieldName = `position-${errorFields[i]}`;
    scroller.scrollTo(fieldName, { offset: -200, smooth: true });
    break;
  }
}

function getErrorFieldNames(obj, name = '') {
     //....this gives me the errors in an array
}
```

My error array works fine and the field Name I got for scrollToFirstError is either "position-name" or "position-address", which is what I expected to. However, Scroller keeps telling me that "Target element could not be found".

My scrollToFirstError was called in onSubmitFail which is an API from redux-Form.

Thank you very much for helping me with this!

**Comment by fisshy** [comment]
Hello,

Try changing className to name=""

**Comment by MattyChance** [comment]
Thank you so much for the help!

It is still not working. It seems that because my form is rendering two vertical scroll bars, scrollTo only works on one of them so it does not scroll all the way to the error fields... I tried to use 'overflow-y: hidden' to disable one of the scrollbars but the rest of the form just does not show up any more....

any hacks on this please?

**Comment by MattyChance** [comment]
closing the issue as I ended up using DOM method: `scrollIntoView()`. Served my purpose well. Thank you for your help!
