### ISSUE TITLE
[Todo]Change the usage which will be deprecated in next React version

### ISSUE THREAD

**Issue by NE-SmallTown** [fisshy/react-scroll#218]
I notice that react-scroll use `React.DOM.xxx` internal,but this usage will be deprecated in next React version.Just like the error message says:

`Accessing factories like React.DOM.div has been deprecated and will be removed in the future. Use the react-addons-dom-factories package instead.`

For more details,please see [react-addons-dom-factories](https://github.com/facebook/react/blob/86dd083f455f71369b4c1bf1e798dd2fd5a3c9c4/packages/react-dom-factories/README.md) and [Create react-addons-dom-factories package #8356](https://github.com/facebook/react/pull/8356)

**Comment by fisshy** [comment]
Thanks for reminding me about it, I will do it or if someone want to PR :)

**Comment by ahutchings** [comment]
I just ran into this with the new React 15.6 release and submitted a PR: #224

**Comment by NE-SmallTown** [comment]
close due to #224
