### ISSUE TITLE
custom handleClick for shallow routing with next.js on Link

### ISSUE THREAD

**Issue by rockchalkwushock** [fisshy/react-scroll#236]
I am using `react-scroll` in a `next.js` project and I want to be able to do shallow routing on the `scrollTo` event. Looking at the docs & source code I am creating my own custom `Element` & `Link` components:

_AppElement.js_

```js
import { Component } from 'react'
import { Helpers } from 'react-scroll'

const { Element } = Helpers

class AppElement extends Component {
  render() {
    const newProps = Object.assign({}, this.props)
    if (newProps.parentBindings) {
      delete newProps.parentBindings
    }
    return (
      <div
        {...newProps}
        ref={el => {
          this.props.parentBindings.domNode = el
        }}
      >
        {this.props.children}
        <style jsx>{`
          div {
            align-content: center;
            display: flex;
            flex-direction: column;
            height: 100vh;
            justify-content: center;
            margin: 0;
            max-width: 100vw;
            padding: 0;
            text-align: center;
            width: 100vw;
          }
        `}</style>
      </div>
    )
  }
}

export default Element(AppElement)

```

_AppLink.js_

```js
import { Component } from 'react'
import { Helpers } from 'react-scroll'

const { Scroll } = Helpers

class AppLink extends Component {
  render() {
    return (
      <a {...this.props}>
        {this.props.children}
      </a>
    )
  }
}

export default Scroll(AppLink)
```

Where I'm running into some problems is understand the `onClick` event that I will be passing on `AppLink`. I see in the [source code]() where `onClick` is a prop and that if it is present it will override the predefined [`handleClick`](). What I'm not understanding is how to get access to `this.props.to` for my custom `_handleClick` method. Do you have any examples or advice in how to handle this use case?

_HomePage.js_

```js
import { Component } from 'react'
import { scroller } from 'react-scroll'
import Router from 'next/router'

import { AppElement, AppLink } from '../components'

class HomePage extends Component {
  _handleClick = (e, to) => {
    e.preventDefault();
    e.stopPropagation();

    // Shallow Routing by Next
    // I want to access this.props.to and append it to the route.
    const href = `/#${to}`
    Router.push(href, href, { shallow: true })

    // Scrolling logic
    scroller.scrollTo(to, {
      // options here
    })
  }
  render() {
    return (
      <div className="application">
        <AppLink
          to="four"
          smooth
          duration={500}
          delay={1000}
          onClick={this._handleClick}
        >
          Link to 4
        </AppLink>
        <AppElement name="one" id="one">
          <h1>Content One</h1>
        </AppElement>
        <AppElement name="two" id="two">
          <h1>Content Two</h1>
        </AppElement>
        <AppElement name="three" id="three">
          <h1>Content Three</h1>
        </AppElement>
        <AppElement name="four" id="four">
          <h1>Content Four</h1>
        </AppElement>
      </div>
    )
  }
}

export default HomePage
```

**Comment by rockchalkwushock** [comment]
I can get the following to work for the shallow routing and the scroll happens but I get no animation or transition at all:

```js
  _handleClick = (e, to) => {
    e.preventDefault()
    e.stopPropagation()

    const href = `/#${to}`
    Router.push(href, href, { shallow: true })

    // scrollTo is working but none of the options passed are taking effect.
    // passing the options on <AppLink /> isn't possible because _handleClick cannot
    // access those 'props', that I know of anyways.
    scroller.scrollTo(to, {
      duration: 1500,
      delay: 100,
      smooth: 'easeInOutQuint'
    })
  }
```

_render_

```js
// passing props on the component will not be registered since native `handleClick` is being overridden.
<AppLink to="four" onClick={e => this._handleClick(e, 'four')}>
   Link to 4
</AppLink>
```

**Comment by rockchalkwushock** [comment]
I see now that `Helpers.Scroll` accepts [2 arguments](https://github.com/fisshy/react-scroll/blob/master/modules/mixins/Helpers.js#L33), the second being a custom defined `scroller`. I will give this a try and close this issue if I succeed in what I'm trying to do. I will also submit any updates to the docs for others since in the second argument is not alluded to in the docs.

**Comment by rockchalkwushock** [comment]
I am a little confused at what is happening [here](https://github.com/fisshy/react-scroll/blob/master/modules/mixins/Helpers.js#L205). We are taking in the props of `Link || CustomLink`; but then we loop over `protoTypes` and remove any props that correspond to both `props` & `protoTypes`. So I'm being left with only `children`, `className`, & `onClick`.

Now later on I can see that these props are made available with the `onClick()`. Is this right? How is the developer suppose to access the props being passed onto `Link` or their `CustomLink` if they are being remove &/or made private being the `onClick` function?

![screen shot 2017-07-07 at 2 17 04 pm](https://user-images.githubusercontent.com/19720404/27973333-55254124-631f-11e7-9605-3b75fba9d431.png)

**Comment by rockchalkwushock** [comment]
Seems as though passing a `customScroller` doesn't alleviate the problem either. I could be approaching this incorrectly. At this point I'm seriously lost on how to implement this:

_customScroller.js_
```js
import { scroller } from 'react-scroll'

const customScroller = {
  scrollTo: (el, opts) => {
    scroller.scrollTo(el, opts)
  }
}

export default customScroller
```

_AppLink.js_

```js
import { Component } from 'react'
import { Helpers } from 'react-scroll'
import PropTypes from 'prop-types'

import customScroller from './customScroller'

const { Scroll } = Helpers

class AppLink extends Component {
  static propTypes = {
    onClick: PropTypes.func.isRequired
  }
  render() {
    return (
      <a {...this.props}>
        {this.props.children}
      </a>
    )
  }
}

export default Scroll(AppLink, customScroller)
```

**Comment by fisshy** [comment]
Is there any reason you have to extend your own link/elements? 

Could be something that's not working with that. 

Does it work if you don't create your own?

**Comment by rockchalkwushock** [comment]
@fisshy 

I had forgot to mention that yes I did try just using the defined `Link` component as well passing the `onClick` prop with custom logic is not working. The shallow routing code will run with no problems but defining the new scroll event will only perform default scroll animation. I can pass whatever options to `scroller.scrollTo` that I want or on the `Link` component it's self but they are not registered..

**Comment by fisshy** [comment]
So could it be that the routing scrolls to the element with the #hash.

Or do you still get the same error without the routing event fired?

**Comment by rockchalkwushock** [comment]
I will check that as soon as I get home. Not sure if I had checked that case or not but I'm thinking no. I'll have an answer for you in about an hour. Thanks for helping out with this.

**Comment by rockchalkwushock** [comment]
That is definitely the issue. I will look into this on the `next` side and see if I can potentially override the scrolling event being called by the shallow routing. I tried inverting the order and calling the `scroller.scrollTo` first but I get a route change, jump to that `#`, back to the previous location and then the scroll event from `react-scroll`.

Thanks for your help in figuring this out. I might just have to forgo the shallow routing idea.

**Comment by fisshy** [comment]
No problem, I'm glad you found the issue.
