### ISSUE TITLE
Not scrolling to bottom

### ISSUE THREAD

**Issue by znat** [fisshy/react-scroll#243]
I'm doing the following, but nothing happens.
Am I missing something?
```
import {animateScroll}  from 'react-scroll';
...
animateScroll.scrollToBottom();
```

**Comment by luskin** [comment]
Same issue here. Anybody else?

**Comment by fisshy** [comment]
@znat are you using this inside react component?

**Comment by luskin** [comment]
@znat, of course. The component is very simple as I am just trying to get it working as a test. The only thing I'm wondering is if this package doesn't work when it's inside another component/div.

**Comment by luskin** [comment]
@znat I went ahead and made the most simple component I could, with three divs eavh taking up the entire screen size. I can scroll this up and down with the mouse, however when I click the button to scrollToBottom it doesn't do anything. Attached is the App component as well as the logs from the scrollEvent. Any help would be greatly appreciated. Thanks.

```import React, { Component } from "react"
import Scroll from 'react-scroll';

let scroll = Scroll.animateScroll;
let Events = Scroll.Events;
let scrollSpy = Scroll.scrollSpy;

export class App extends Component {

  componentDidMount() {
    Events.scrollEvent.register('begin', function(to, element) {
      console.log("begin", arguments);
    });

    Events.scrollEvent.register('end', function(to, element) {
      console.log("end", arguments);
    });

    scrollSpy.update();
  }

  // render
  render() {
    return (
      <div id="main" style={{ overflowY: 'scroll' }}>
        <button onClick={() => scroll.scrollToBottom()}>Scroll To Bottom</button>
        <div className='yellow' style={{ height: '100vh', width: '100vw', backgroundColor: 'yellow' }} />
        <div className='red' style={{ height: '100vh', width: '100vw', backgroundColor: 'red' }} />
        <div className='green' style={{ height: '100vh', width: '100vw', backgroundColor: 'green' }} />
      </div>
    )
  }
}

export default App
```

The logs are as follow:

![screen shot 2017-08-10 at 12 08 29 pm](https://user-images.githubusercontent.com/5702322/29187521-e47e8064-7dc4-11e7-9a6c-abb16835e617.png)

**Comment by luskin** [comment]
Figured it out eventually! For anyone else having problems you need to use the option props to pass in a containerId of the div you'd like to scroll in. In my above code, this would be "main", otherwise it tries to scroll the window which has a 100% height set already! Hope this helps someone else.

**Comment by fisshy** [comment]
Ah great, glad you solved it. Closing the issue then.

**Comment by znat** [comment]
Hi @luskin and @fisshy 
Thank you for your comments, I was out for a few days.
Yes, I am using it inside a React component. @luskin I don't understand what you mean with _use the option props to pass in a containerId of the div you'd like to scroll in_ ?
What did you change exactly in your code above.
Thank you
