### ISSUE TITLE
showing anchor ids as location hash in url

### ISSUE THREAD

**Issue by sionelt** [fisshy/react-scroll#261]
Is there any way to show and update the url with the current location.hash like www.domain.com/#hash base on the anchor id linked to?

**Comment by fisshy** [comment]
Now there is, check out latest version.

**Comment by vkosovskikh** [comment]
@fisshy 
`react-scroll@1.7.11`

No `href` attribute on `<a>` provided by `<Link>` component. And even if specify `href` like this:
```
<Link to="somewhere" href="#somewhere" />
```
the hash in url isn't updating after click on link.

**Comment by vkosovskikh** [comment]
Okay, I figured out that hash is changing only with `hashSpy` option. The second problem was that with page zoom maybe offsets are not accurate.
