### ISSUE TITLE
Change to package.json in 1.6.0 breaks import

### ISSUE THREAD

**Issue by erinmeyers88** [fisshy/react-scroll#266]
package.json in 1.5.5:
"main": "modules",

package.json in 1.6.0
"main": "build/npm/modules"

My build is breaking because it can't resolve this location.

**Comment by JonyTek** [comment]
Same here.

**Comment by VinZ1A** [comment]
same for me

**Comment by gennaroanesi** [comment]
Same here. 😞

**Comment by joshua703** [comment]
FWIW 1.5.5 also seems to work fine. It appears that this line was removed: https://github.com/fisshy/react-scroll/commit/15584747b85ff90f6aefd0e19e46df14a5b07024, but is still being referenced in https://github.com/fisshy/react-scroll/blob/15584747b85ff90f6aefd0e19e46df14a5b07024/package.json#L5.

**Comment by vhmth** [comment]
Samesies!

**Comment by paulius005** [comment]
Samesies!

**Comment by fabioespinosa** [comment]
Thanks @VinZ1A and @erinmeyers88 I was going crazy trying to find the error in my code

**Comment by fisshy** [comment]
So sorry guys, fixed it in 1.6.1. Somehow that line changed on my latest merge and I was to tired to notice it. Sorry :(

**Comment by fabioespinosa** [comment]
Thanks a lot @fisshy 👍  great job fixing it fast

**Comment by antoniocapelo** [comment]
Not 100% if related but ever since I updated to 1.6.1, this lib stopped working. It doesn't throw any errors, but the spy/scroll to functionality stopped working.
