### ISSUE TITLE
Setting Link active state seems to be broken in v1.6.4

### ISSUE THREAD

**Issue by mariusespejo** [fisshy/react-scroll#267]
I've noticed that after upgrading, the active state of a Link never gets set. `onSetActive` prop also never gets called. I am guessing it's related to the [recent refactors](https://github.com/fisshy/react-scroll/commit/37aa9391ab0e84cab57825d06c82edfc499b8655) done on Helpers.js

Downgrading to v1.5.5 works but it seems like in general there is something off with the state management of the active links. For instance in v1.5.5 I've found refreshing the page makes active state malfunction similar to what's mentioned in #193 and #124. It looks like spy/active state is a recurring issue: #250, #125, #29

**Comment by fisshy** [comment]
Thanks for noticing it. Let me look into it - and If you find the issue please feel free to make a PR :)

**Comment by fisshy** [comment]
I've tried to reproduce this error, but can't find a way to reproduce it. I will continue to try :)

**Comment by mariusespejo** [comment]
Thanks for trying, I'm curious is the [demo you have here](http://fisshy.github.io/react-scroll-example/basic/index.html) running on the latest version?

**Comment by fisshy** [comment]
Currently not. Take down the latest and run the examples. Just published some new changes, might solve your issue as well :)

**Comment by vincentracine** [comment]
Issue is also present in v1.6.3

**Comment by karaschee** [comment]
also in 1.6.4

**Comment by mariusespejo** [comment]
@fisshy I was able to reproduce the issue in another project, but I'm not entirely sure yet how to fix it

Check out this running demo: https://stackblitz.com/edit/react-gdky2y

Notice that there is an import line for the semantic-ui css, that seems to induce the issues. You'll notice in the demo the links never get set to active. If you comment out that import it gets fixed, and active states get set, links become yellow. 

So the issue seems to be completely based on css and my guess is there is some sort of collision on class names around links/anchors?

I know that semantic-ui is a separate project but I would guess that you'd probably want this library to play nicely with other css frameworks. I'm guessing the others that have commented above are probably running into the same thing as well due to their own css.

Any thoughts there?

Code:
```javascript
import React, { Component } from 'react';
import { render } from 'react-dom';
import { Element, scrollSpy, Events, Link } from 'react-scroll';
import './style.css';
import 'semantic-ui-css/semantic.min.css'; //this breaks active styling

class App extends Component {
  constructor() {
    super();
    this.state = {
      name: 'React'
    };
  }

  render() {
    return (
      <div>
        <h1>test </h1>
        <div className="nav">
          <Link to="test1" spy={true} smooth={true} duration={500} offset={-50}>
            Test 1
        </Link>
          <Link to="test2" spy={true} smooth={true} duration={500} offset={-50}>
            Test 2
        </Link>

          <Link to="test3" spy={true} smooth={true} duration={500} offset={-50}>
            Test 3
        </Link>
        </div>
        <Element name="test1" className="fake-height">
          <div className="">test 1 </div>
        </Element>
        <Element name="test2" className="fake-height">
          <div className="">test 2 </div>
        </Element>
        <Element name="test3" className="fake-height">
          <div className="">test 3 </div>
        </Element>
      </div>
    );
  }
}

render(<App />, document.getElementById('root'));
```
style.css is just:
```css
h1, p {
  font-family: Lato;
}

.fake-height {
  height: 1200px;
}

.nav {
  position: fixed;
  top: 0;
  width: 100%;
  background: gray;
}

.active {
  color: yellow;
}
```

**Comment by mariusespejo** [comment]
So I did a little bit more digging and found what exactly from the css was causing the issues.

The semantic css was setting `overflow-x: hidden` on the body of the html. I was able to resolve the active style issue by overriding that to be `overflow-x: visible`. 

@fisshy I'm not familiar with the codebase but taking a quick look at the spy handler, I'm guessing when you're trying to get the coordinates of an element with `element.getBoundingClientRect()` the result of that differs with overflow. I don't know enough here to do a PR but hope that helps.

Thanks for your time.

**Comment by fisshy** [comment]
Thanks alot for your digging. How would you even scroll if overflow is hidden, that makes scrolling impossible?

**Comment by mariusespejo** [comment]
Well what I mentioned was `overflow-x` specifically in my case was the issue which is clips the left and right side of an element if set to `hidden`. So to answer your question, it doesn't directly have anything to do with scrolling up and down but seems to still affect scroll spy somehow. 

If I get a chance I can try to reverse engineer what you guys are doing to do the spying and see why overflow-x is affecting it but I don't have a ton of time right now. You can close this issue if you want to, but I feel like there's still an underlying issue there.

**Comment by fisshy** [comment]
I'm not gonna close it, I will lable it as a bug. And will obviously try to solve it before the week ends, but my time is limited atm.

**Comment by alexanderfrey** [comment]
I'm also running into this problem :( deactivating overflow-x: hidden on root div does somehow affect this but not solve it since I have to click the link 2 times in order to trigger an active state.

**Comment by fisshy** [comment]
Gonna look into this today, might be solved by the end of the day.

**Comment by fisshy** [comment]
I've solved this one in the latest commit, but I've not published it yet.

The problem was that the scoll wasn't getting triggered on the body element.

Can someone help me verify it works? All tests passes and the examples work. 

I added an example with your code as well.

`$ npm run examples`

Navigate to http://localhost:8080/with-overflow-x/index.html

https://github.com/fisshy/react-scroll/commit/974ae313d5b4eb4feac00338f6293727977ec3ef

**Comment by karaschee** [comment]
I found it worked if I remove the `scroll-y: auto` from `body` based on the latest commit. The right container is `document`, but getScrollSpyContainer method give me `body` if `scroll-y: auto` exists. I need use this style for some trick, so I set `container` prop on `Link` strictly at last.

**Comment by fisshy** [comment]
Checkout v1.6.5 and let me know if that one solves this.

**Comment by mariusespejo** [comment]
Just tried it on the same example app I posted before/above (which breaks with semantic-ui css on previous versions), looks fixed to me with v.1.6.7

Example: (active link should be yellow)
https://react-gdky2y.stackblitz.io/

Thanks @fisshy !

**Comment by fisshy** [comment]
Great! No problem! :)

**Comment by gregoralbrecht** [comment]
Am I missing something here? I'm currently having the same issue and the example linked by @mariusespejo doesn't seem to work?

**Comment by jolgo1989** [comment]
someone helpme please, I am working with the react-scroll library, the problem is that when I click on the about and skill buttons, the active style is not being applied.

export const navLinks = [
  {
    id: 1,
    text: "Home",
  },
  {
    id: 2,
    text: "About",
  },
  {
    id: 3,
    text: "Porfolio",
  },
  {
    id: 4,
    text: "Skill",
  },
];

//Menu
const Menu = () => {
  return (
    <div>
      <nav className="nav">
        <ul className="ul">
          {navLinks.map((link) => (
            <li key={link.id}>
              <Link
                to={link.text}
                activeClass="active"
                spy={true}
                smooth={true}
                duration={500}
              >
                <a className="item" href="#">
                  {link.text}
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
};
//Components
const about = () => {
  return (
    <div className="divAbout" id="About">
      About
    </div>
  );
};

const skill = () => {
  return (
    <div className="divSkill" id="Skill">
      Skill
    </div>
  );
};

//Styles
.active {
  background-color: #05bd0b;
  
}
