### ISSUE TITLE
Memory leak: cancel-events event listeners are never deregistered

### ISSUE THREAD

**Issue by sleexyz** [fisshy/react-scroll#268]
For every call to `animateTopScroll`

a new set of event handlers on `document` are created.

https://github.com/fisshy/react-scroll/blob/886a792b10e4c72731c3652c5922583e165b4798/modules/mixins/animate-scroll.js#L150

https://github.com/fisshy/react-scroll/blob/886a792b10e4c72731c3652c5922583e165b4798/modules/mixins/cancel-events.js#L5

We never deregister those event handlers when we are finished with the scroll.

**Comment by fisshy** [comment]
Good catch, looking into it.

**Comment by fisshy** [comment]
Event's should get removed in latest commit. 

https://github.com/fisshy/react-scroll/commit/eda9f2b9dac503b6741fcbf0619a12c5f74517c1

Not published yet.

**Comment by sleexyz** [comment]
Nice, tested manually and works for me :)

**Comment by sleexyz** [comment]
fixed by #271
