### ISSUE TITLE
ReactDOM Error

### ISSUE THREAD

**Issue by alanzanattadev** [fisshy/react-scroll#27]
Hi, i've just encountered an error at this line : 
scroller.register(this.props.name, ReactDOM.findDOMNode(this)); in Helpers.js

Uncaught TypeError: o.findDOMNode is not a function

I think it's because react-dom is not a dependency in the package.json of npm build. But even after adding the package, the error is persisting.

I have just placed a link and an element as in your exemple, and installed react-scroll and react-dom with npm. The "to" and "name" property of link and element are the same.

I'm sorry for my english errors.

Thanks

**Comment by fisshy** [comment]
Thanks for the issue! Will look into it.

**Comment by alanzanattadev** [comment]
Than you ! I'm using react-scroll for a website which passes in production soon, how much time will it take to be fixed ?

**Comment by fisshy** [comment]
Should be solved with the latest merge.
