### ISSUE TITLE
scrollTo function is broken

### ISSUE THREAD

**Issue by podrivo** [fisshy/react-scroll#272]
Hello.

I have a project using React + Next, and I've recently updated to React 16 and Next 4.
And after this updates, `react-scroll` stopped working. I'm not sure it's related, but that's the main change I've made recently.

I'm using `v1.6.4`

That's how it's setup:
```
import Scroll from 'react-scroll'
let Element = Scroll.Element
let scroller = Scroll.scroller
```
```
scrollTo = () => {
    scroller.scrollTo('element', {
      duration: 800,
      delay: 0,
      smooth: 'easeInOutQuart',
      containerId: 'element'
    })
  }
```
```
<MainButton href="javascript:void(0)" onClick={this.scrollTo}>Click me</MainButton>
```
```
<Element id="element" name="element"></Element>
```

Any clues on why it's not working?
Thanks

**Comment by dongapplyboard** [comment]
Having the same problem. ScrollTo as well as Link are both not working.

**Comment by fisshy** [comment]
```
scrollToWithContainer() {
  scroller.scrollTo('scroll-container-second-element', {
        duration: 800,
        delay: 0,
        smooth: 'easeInOutQuart',
        containerId: 'scroll-container'
  })
}

 <li><a className="test1" to="test1" onClick={() => this.scrollToWithContainer()} >Scroll to element within container</a></li>

 <Element name="test8" className="element" id="scroll-container" style={{
          position: 'relative',
          height:'200px',
          overflow:'scroll',
          marginBottom: '100px'
        }}>

          <Element name="scroll-container-first-element" style={{
            marginBottom: '200px'
          }}>
            first element inside container
          </Element>

          <Element name="scroll-container-second-element" style={{
            marginBottom: '200px'
          }}>
            second element inside container
          </Element>

</Element>
```

This seems to be working for me, except it doesn't scroll to the container. 

Does the scrolling inside the container still work?

**Comment by fisshy** [comment]
I've pushed some extra examples https://github.com/fisshy/react-scroll/commit/bfddbe665b421ab5f5f1f8f05ca7c812026a55bb

Can you try it and see if it works as expected?

`npm start` and then navigate to `http://localhost:8080/basic/index.html`

**Comment by podrivo** [comment]
I was able to make it work, but unfortunately I'm not sure what was the mistake...
Thanks, @fisshy !

**Comment by fisshy** [comment]
I think the problem was that the ` containerId: 'scroll-container' ` was set and that tells the scroller to look for a container to scroll and not the document.

**Comment by podrivo** [comment]
Despite the differences between the codes I've shared, the `containerId` wasn't set before this and still wasn't working. I think this is related to which element you place the `name` tag. But again, I'm not sure...

**Comment by developer-lindner** [comment]
So, it's still broken?

**Comment by developer-lindner** [comment]
Moved back to v1.5.4 which works properly. 1.6.x seems broken to me...

**Comment by podrivo** [comment]
@developer-lindner I was able to make it work, by moving the element with the `name` tag. I think it has to be on the same level as the trigger.

**Comment by tonoslav** [comment]
@podrivo what do you mean by "same lavel as trigger" what is trigger ? 

@fisshy if you want this can fix it (at least it helped me)

In **scroller.js** line **75** add

```js
scrollOffset = target.getBoundingClientRect().top + window.scrollY
```

Remove rest above related to `scrollOffset`

For me this solution works but I don't use containers but I think with this solution it doesn't matter 
Please try to implement it somehow, I need this to work
