### ISSUE TITLE
Anchor Links not Working if inside a div with overflow-x : scroll

### ISSUE THREAD

**Issue by kunal-arora** [fisshy/react-scroll#275]
I am not able to get this working for my project. Here is the [link](https://github.com/gitserverhu/ustraa_v2_react/blob/feature/mobileCategoryPage/v1.2/app/components/AllProductsPage/index.js#L41) to the code. 

If I remove the overflow-x from SubCategoriesWrapper component, then the links work fine.
Thanks in advance.

**Comment by louischeung2557** [comment]
I have the same issue if i use div with overflow:auto to wrap the Link component, it will not working, I tried to add overflow with setTimeout function but the spy will no response. any idea to fix this issue?

thank you very much in advanced

**Comment by ValentinH** [comment]
Same here too 🙁

**Comment by ValentinH** [comment]
Reproduction example:
[![Edit react-scroll overflow-x bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m59z23yq0y)

**Comment by fisshy** [comment]
I do believe I've solved this, but I haven't published anything.

Can you try with the latest commit? 

https://github.com/fisshy/react-scroll/commit/974ae313d5b4eb4feac00338f6293727977ec3ef

**Comment by ValentinH** [comment]
Great! I'm trying it right now ;)

**Comment by ValentinH** [comment]
Your example does work, but it doesn't use `overflow-x`. 
If I use the following style on nav, it breaks:
```css
.nav {
  position: fixed;
  top: 0;
  width: 100%;
  background: #ededed;
  overflow-x: auto;
}
```

**Comment by ValentinH** [comment]
If I return the document instead of parent, it works:
```js
if (
    overflowRegex.test(style.overflow) ||
    overflowRegex.test(style.overflowX)||
    overflowRegex.test(style.overflowY)
  ) {
    return document
}
```

**Comment by fisshy** [comment]
Ah I see, 

I'm thinking of removing auto finding overflow-parent, I think setting the container is good enough.

**Comment by ValentinH** [comment]
Indeed, I didn't understand the logic at first: actually just removing the check about overflow is fine. But I'm not sure of what it was there in the first place.

**Comment by fisshy** [comment]
I did some changes, can you try this commit.

Now fallbaking on document if containerId isn't set.

https://github.com/fisshy/react-scroll/commit/8e9757cd325e148583693a440f30c4cb537f44e6

**Comment by ValentinH** [comment]
Looks good to me! 👍

**Comment by ValentinH** [comment]
Do you plan to bump a new version soon?

**Comment by fisshy** [comment]
Yes, hold on! :)

**Comment by fisshy** [comment]
v1.6.5 is now out

**Comment by ValentinH** [comment]
Thank you really much, my issue is resolved now 🎉

**Comment by fisshy** [comment]
No problem, glad to help! :)
