### ISSUE TITLE
1.6.7 broke IE scroll links

### ISSUE THREAD

**Issue by Maarten88** [fisshy/react-scroll#284]
I upgraded react-scroll to the latest version, and found that all scoll links worked incorrectly in IE (tested version 10 and 11), they jump directly to the page top. Reverting to 1.6.5 fixed the issue.

**Comment by ctkc** [comment]
I have the same issue.

**Comment by fisshy** [comment]
Does v1.7.3 work for you? @ctkc  @Maarten88

**Comment by ctkc** [comment]
Yes!, v1.7.3 works in IE 10 and 11.

Thanks!
