### ISSUE TITLE
Active link issues

### ISSUE THREAD

**Issue by aprather51** [fisshy/react-scroll#289]
The issues following [ #267](https://github.com/fisshy/react-scroll/issues/267) and [#193](https://github.com/fisshy/react-scroll/issues/193) I am not sure I understand if this have been resolved?  No indication as [bug](https://github.com/fisshy/react-scroll/labels/bug)?

**Comment by fisshy** [comment]
It should be fixed, otherwise provide me with a plunker and how I can reproduce it. @aprather51

**Comment by aprather51** [comment]
I doubt anything need to be reproduced.  Everything seem to work fine except for a little glitch with incorrect active on menu bar as mentioned in [#193 ](https://github.com/fisshy/react-scroll/issues/193). 

e.g. Following from this live [demo](http://fisshy.github.io/react-scroll-example/basic/index.html)
(Note: It does not work with Firefox 57.0 and Firefox Web Developer Edition 58.0b10)

Clicking on "Test 2", You will notice active menu will stuck on "Test 1".  Even though, it did scroll correctly into "Test 2" section/element.  When clicking on "Test 3" menu, will again scroll correctly into "Test 3" section/element. The active menu that stuck on "Test 1" will  skip over "Test 2" and then into "Test 3" -- On the correct active menu. Other thing,  you will have to Double Click on menu for active menu to match with section. That some glitch that need to be fixed rather than reproduce it. 

With my time limit, I doubt I could find time to solve this issue. Hopefully, my feedback can help one to fix the issues.

**Comment by mariusespejo** [comment]
I was the one who closed out #267 after testing it. At the time it was fixed. But I noticed after the Helper stuff was deprecated definitely saw some issues with active links again after updating.
