### ISSUE TITLE
window.scrollY not supported on internet explorer

### ISSUE THREAD

**Issue by dwigt** [fisshy/react-scroll#290]
I do not know if this is a bug, but have you found a way to make react-scroll work on IE out of the box?

Inside utils the variable scrollOffset is set using window.scrollY which is not supported on internet explorer. pageYOffset offers a more universal alternative, but maybe there is a reason you are using scrollY or can it be polyfilled?

**Comment by fisshy** [comment]
It should work on IE.

Do you have the latest version?

https://github.com/fisshy/react-scroll/blob/8aa2c8db7fdb686a57ca4df0af83fb5e654be77d/modules/mixins/utils.js#L26

**Comment by dwigt** [comment]
Thanks, updating from 1.6.7 to 1.7.0 seems to have fixed the issue!
