### ISSUE TITLE
v1.7.2 is a breaking change

### ISSUE THREAD

**Issue by isaachinman** [fisshy/react-scroll#291]
Am I missing something here? Just experienced a `TypeError` in my application due to a breaking change being introduced as a minor version bump. Here are the [semver docs](https://semver.org/) for anyone unfamiliar...

If you check [this commit](https://github.com/fisshy/react-scroll/commit/a1c25a265f19167a7b67731d3d347f5bc4f2f2db), you'll see the import changes from `default` to `*`.

This is a breaking change. Eg:

    import Scroll from 'react-scroll'
    <Scroll.Element />

Now throws: `Cannot read property 'Element' of undefined`.

Should be relatively easy to fix this with some git re-ordering, not sure about `npm` though. You'll probably need to unpublish that version.

**Comment by fisshy** [comment]
Thanks for the issue.

No it was not a major, it was a default export missing.

Thanks for pointing it out, please grab the newest version, v1.7.4

https://github.com/fisshy/react-scroll/commit/9ee363cf3f67997b93711ad9981d6c2d15a84c56

**Comment by isaachinman** [comment]
Okay. Maybe add test coverage for exports.

**Comment by fisshy** [comment]
Should definitely do that! 👍
