### ISSUE TITLE
Firefox 58.0b11 MacOS fails to scroll to elements

### ISSUE THREAD

**Issue by Kingles** [fisshy/react-scroll#292]
### Bug description:

Using the latest version of Firefox, (58.0b11), clicking a `<Link>` component with a valid `to` attribute does not have the expected outcome

### Reproduction steps:

 * navigate to the live demo (http://fisshy.github.io/react-scroll-example/basic/index.html)
 * click any of the navigation buttons, e.g. `Test 1`, `Test 2`, etc.
 * observe that the window does not scroll at all

### Expected Outcome

When clicking a `<Link>` with a valid `to` attribute, `react-scroll` will scroll the viewport such that the element with the `name` attributed specified in the `to` attribute of the `<Link>` component is visible in the viewport.

### Actual Outcome

The viewport does not scroll at all, nothing happens (visible to the user) on click. 
console output:
```
ReferenceError: event is not defined [Learn More]
onClick
http://fisshy.github.io/react-scroll-example/build/basic/app.js:322:1
onClick self-hosted:952:17 executeDispatch
http://fisshy.github.io/react-scroll-example/build/basic/app.js:3545:21
executeDispatch
http://fisshy.github.io/react-scroll-example/build/basic/app.js:14948:23
forEachEventDispatch
http://fisshy.github.io/react-scroll-example/build/basic/app.js:3533:5
executeDispatchesInOrder
http://fisshy.github.io/react-scroll-example/build/basic/app.js:3554:3
executeDispatchesAndRelease
http://fisshy.github.io/react-scroll-example/build/basic/app.js:2925:5
forEachAccumulated
http://fisshy.github.io/react-scroll-example/build/basic/app.js:16845:5
processEventQueue
http://fisshy.github.io/react-scroll-example/build/basic/app.js:3130:5
runEventQueueInBatch
http://fisshy.github.io/react-scroll-example/build/basic/app.js:10405:3
handleTopLevel
http://fisshy.github.io/react-scroll-example/build/basic/app.js:10431:5
handleTopLevelImpl
http://fisshy.github.io/react-scroll-example/build/basic/app.js:10517:5
perform
http://fisshy.github.io/react-scroll-example/build/basic/app.js:15921:13
batchedUpdates
http://fisshy.github.io/react-scroll-example/build/basic/app.js:9148:7
batchedUpdates
http://fisshy.github.io/react-scroll-example/build/basic/app.js:14144:3
dispatchEvent
http://fisshy.github.io/react-scroll-example/build/basic/app.js:10612:7
dispatchEvent self-hosted:994:17
```

**Comment by Kingles** [comment]
Also worth noting that the same issue occurs in Firefox Focus (for Android)

**Comment by fisshy** [comment]
Can you try pull the project and run the examples local? 

The live code is not reflected to the latest versions.

All tests passes in Firefox, so it should work.

**Comment by vcolavin** [comment]
I can confirm that the live example fails on Firefox Developer Edition 58.0b9, but pulling the project and running local examples works fine.
