### ISSUE TITLE
How to scroll a view when on click of element in another scrollable view

### ISSUE THREAD

**Issue by Thilagm** [fisshy/react-scroll#297]
Hi,

I have a requirement in which i have 3 scrollable views. When i click a element in one scrollable e.g 3 i should scroll another scrollable view e.g 2.

**Comment by fisshy** [comment]
Hi,

It should be possible, try somthing like this

`
<Link activeClass="active" to="first" spy={true} smooth={true} duration={250} containerId="scrollContainer1">Scroll first element</Link>

<Element name="container" className="element" id="scrollContainer1">
   <Link activeClass="active" to="second" spy={true} smooth={true} duration={250} containerId="scrollContainer2">Scroll second elementt</Link>

     <Element name="first" className="element">first element inside container</Element>
</Element>
 

<Element name="element2" className="element big" id="scrollContainer2>

     <Element name="second" className="element">secondelement inside container</Element>

</Element>
   
`

**Comment by Thilagm** [comment]
It works fine. Thanks
