### ISSUE TITLE
How to make a div with scroll attribute how can I make react-scroll scroll in there? 

### ISSUE THREAD

**Issue by spaceforestchu** [fisshy/react-scroll#302]
Hi guys,

My goal is that when I click on a Mark the react-scroll will go to the selected list element. 
I am not getting any errors. From my research, it is because the react-scroll isn't moving the div with scroll attribute. 

How can I make react scroll that moves the div scroll instead of the window scroll?

![screen shot 2018-01-23 at 7 12 37 pm](https://user-images.githubusercontent.com/15354386/35307727-2b717f64-0072-11e8-8ee9-8687dd4b8722.png)

<img width="841" alt="screen shot 2018-01-23 at 7 12 54 pm" src="https://user-images.githubusercontent.com/15354386/35307760-5db95ece-0072-11e8-8790-66d8cb1cd087.png">

![screen shot 2018-01-23 at 7 18 54 pm](https://user-images.githubusercontent.com/15354386/35307763-62f0477c-0072-11e8-808a-ea2702df6f51.png)

thanks

**Comment by fisshy** [comment]
Hey,

You could solve it by telling the <Link /> to target a container. 

```
<Link to="venue1" containerId="venues">
          Venue 1
</Link>

<Link to="venue2" containerId="venues">
          Venue 2
</Link>

<div className="element" id="venues">
          <Element name="venue1">
             Venue 1
          </Element>

          <Element name="venue2">
             Venue 2
          </Element>
</div>
```

**Comment by fisshy** [comment]
Did you solve it?

**Comment by spaceforestchu** [comment]
Hey didn't see this until now. 

Yes, I did. Thanks much
