### ISSUE TITLE
Media query and spy

### ISSUE THREAD

**Issue by Jun711** [fisshy/react-scroll#303]
I am using media query to decide if a menu bar or a hamburger menu should be displayed but I noticed that spy will only set the first component that it encounters as active and thus, it only works for the menu that is placed first in the template. 

I wonder what is a good way to deal with this? Should I use JavaScript to determine screen size to decide when I should have spy on? 

Thanks!
```
export default class NavHeader extends Component {
  render() {
    const scrollConfig = {
      activeClass: 'active',
      spy: true,
      offset: this.props.shrink ? -60 : -84,
      smooth: 'easeInOutQuad',
      duration: 700
    };

    return (
      <NavContainer>
        <NavigationBar shrink={this.props.shrink} scrollConfig={scrollConfig}/>
        <Burger shrink={this.props.shrink} scrollConfig={scrollConfig}/>
      </NavContainer>
    );
  }
}
```

**Comment by fisshy** [comment]
I'm not sure if this is solveable, but one possible solution could be to listen to the "onSetActive" event on Link, and then update the Link in the burger.

**Comment by Jun711** [comment]
@fisshy Hi Joachim, I think onSetActive is only triggered when activeClass is assigned to an element / component. 
I think it works by using JavaScript to debounce and determine screen size and window resize event; then, assign toggle spy on the right component and update the component's state.

**Comment by fisshy** [comment]
@Jun711 Hi, yes that one possible solution to solve it as well.
