### ISSUE TITLE
TypeError: scroll.scrollToBottom is not a function

### ISSUE THREAD

**Issue by wzup** [fisshy/react-scroll#305]
Why is that?

```
TypeError: scroll.scrollToBottom is not a function
```

Config:
```
import { Element, Events, scroller, scroll } from 'react-scroll'

<Element name={'element'} style={{height: "800px", backgroundColor: '#F6F8FA'}}>
            </Element>;

    scrollTo() {
        scroll.scrollToBottom();
    }

componentDidMount() {
    this.scrollTo();
}
```

**Comment by fisshy** [comment]
Hi,

Use animateScroll.

`import { Link, DirectLink, Element , Events, animateScroll as scroll, scrollSpy, scroller } from 'react-scroll'`

**Comment by wzup** [comment]
@fisshy 
Do I need to specify all those definitions in `componentDidMount()`? You do not explain. You just showed the code. But do we need to use it?

```
  componentDidMount: function() {
    Events.scrollEvent.register('begin', function(to, element) {
      console.log("begin", arguments);
    });
    Events.scrollEvent.register('end', function(to, element) {
      console.log("end", arguments);
    });
    scrollSpy.update();

  },
```

**Comment by wzup** [comment]
Ok, `animateScroll` seems to work.
However, scroll action updates Component. And after `scrollToBottom` happened Component returns to its initial state - zero scroll. Why does it happen? How to persist scrolled offset?

**Comment by fisshy** [comment]
Not sure, make a new issue and provide a way to reproduce it.
