### ISSUE TITLE
Element should have a props to set custom css class on scroll event executed completely.

### ISSUE THREAD

**Issue by KPSoftec** [fisshy/react-scroll#306]
Element should have a props to set custom css class on scroll event executed completely.

I have a link and i want to scroll to particular element on its click but now i want to set custom css blinking border to that element on scroll complete.

same like active class on link on scroll complete.

**Comment by fisshy** [comment]
You can subscribe to onSetActive and update your element yourself.

**Comment by KPSoftec** [comment]
I don't want to set a class on link i wanted to perform action on element.
and while using onSetActive function on Link it does not have element as input parameter to the function..
