### ISSUE TITLE
Q: can get vertical scroll position (window.scrollY) thru this library?

### ISSUE THREAD

**Issue by bob-lee** [fisshy/react-scroll#307]
I liked to have an icon to scroll-to-top when my page was scrolled down and with this helpful library, that was nice and easy.. but with a small side effect: 

I used to monitor `window.scrollY` value to show the icon and after adding this library, its value doesn't seem to be as responsive as before (slow to increase, not decreasing, not resetting after scrollToTop, etc.).

**Comment by fisshy** [comment]
Currently no support for vertical scroll/position. Couldn't you reset window.scrollY by yourself when calling scrollToTop?

**Comment by bob-lee** [comment]
Ok, I had to addEventListener for scroll and get `window.scrollY` inside it. Now it responds well as expected. Closing this issue.
