### ISSUE TITLE
Meteor has conflict with react-dom npm

### ISSUE THREAD

**Issue by newsiberian** [fisshy/react-scroll#31]
Hello,

I ran into a problem trying to use react-scroll in Meteor. The problem is that the react-scroll uses a react-dom npm as dependency, which is not in "Meteor". As a result, when you try to connect react-scroll to a component, an error appears:
![post_image2](https://cloud.githubusercontent.com/assets/11130487/9821261/a127c3a2-58d2-11e5-894a-df6d901bdea1.png)

**Comment by newsiberian** [comment]
I've got an additional information about my problem:
![post_image3](https://cloud.githubusercontent.com/assets/11130487/9830781/d7835966-5954-11e5-9d80-21c8a076dd5e.png)
There is no such function (findDOMNode) in ReactDOM.

**Comment by fisshy** [comment]
Hey!

Try use an older version of react-scroll or upgrade to React v0.14

**Comment by newsiberian** [comment]
Thank you. My miss.
