### ISSUE TITLE
Should you use requestAnimationFrame?

### ISSUE THREAD

**Issue by cheeZery** [fisshy/react-scroll#311]
Just a quick question: Does it make any difference if you wrap all calls to ``scrollTo`` with ``requestAnimationFrame``, or does ``react-scroll`` uses it anyway on every scroll animation?

```
  import { scroller } from "react-scroll";

  scroller.scrollTo(
    "myContainerId",
    {
      duration: 1000,
      delay: 500,
      smooth: true,
      isDynamic: true
    }
  );
  
  // .. same as ..
  
  window.requestAnimationFrame(() => {
    scroller.scrollTo(
      "myContainerId",
      {
        duration: 1000,
        delay: 500,
        smooth: true,
        isDynamic: true
      }
    );
  });
```
We experienced some lags without ``requestAnimationFrame`` but the source might be something else.
Or is that what ``animateScroll`` is for?

**Comment by fisshy** [comment]
scroller.scrollTo should use requestAnimateFrame. But if you want to scroll directly without using the predefined elements, I would use animateScroll directly. 

https://github.com/fisshy/react-scroll/blob/master/modules/mixins/animate-scroll.js#L26

**Comment by cheeZery** [comment]
Thanks, Joachim! I think you answer should be sufficient. I'm pretty sure the lags come from the fact, that at the same time an API is called and the response is stored in some observables (MobX) which in turn causes a lot of re-rendering (React). So if you don't mind I suggest this issue can be closed.
Thanks again!

**Comment by fisshy** [comment]
No problem! I'm glad to help :)
