### ISSUE TITLE
Dynamic offset.

### ISSUE THREAD

**Issue by danielverejan** [fisshy/react-scroll#317]
If you have on the page a fixed navbar which changes height based on viewport width(ex: iPad landscape vs portrait) I would need to set the offset based on the navbar height for it to scroll to the correct position.

Currently I didn't find any way to use dynamic offset except ignoring every component from react-scroll and use `scroller.scrollTo(...)` to recreate that functionality which isn't very pretty as you lose event handlers, activeClass, spy/hashSpy etc.

**Comment by fisshy** [comment]
Wouldn't it be possible to setState when the viewport changes? 

And you just update the offset of the element. 

Or you keep the same offset  of the elments and change the margin-top of the first element?

**Comment by danielverejan** [comment]
Didn't thought about keeping offset on state. Just tested that and it works. Can't use there the margin-top as I have a section where it needs to scroll a bit more then the rest and still count the header height.
Anyway the state works. Thanks for help.
