### ISSUE TITLE
How do I use this with a table?

### ISSUE THREAD

**Issue by Ashwin117** [fisshy/react-scroll#321]
I'm trying to attach an element to a td in a table.

```
<table>
   <tr>
     <td> {value} </td>
  </tr>
</table>
```
I tried wrapping `Element` around the `{value}`, but that didn't work. So I wrapped `Element` around `td`, which started to work, but the console threw errors saying that `div` cannot be a child of `tr`.

What else can I do?

**Comment by fisshy** [comment]
This might be a solution to your problem. 

```
var MyTd = React.createClass({
  render: function () {
    return (
      <td{...this.props}>
        {this.props.children}
      </td>
    );
  }
});

<table>
<tr>
  <MyTd>{value}</MyTd >
</tr>
</table
```

**Comment by Ashwin117** [comment]
Yep, it works. Any reason why it can't work inline? Seems a bit silly.

**Comment by fisshy** [comment]
Not sure to be honest, might be that the element cant be found or to small. Haven't tried it out.
