### ISSUE TITLE
React does not recognize the `containerId` prop on a DOM element

### ISSUE THREAD

**Issue by corysimmons** [fisshy/react-scroll#332]
```
Warning: React does not recognize the `containerId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `containerid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

?

**Comment by corysimmons** [comment]
https://reactjs.org/warnings/unknown-prop.html

[Reduced test case](https://codesandbox.io/s/311jpmwrm5)

**Comment by SamWyld** [comment]
Hi @corysimmons,
I maybe wrong but I don't think that you meant to give the `Element` component the `containerId`.
I think that the containerId is used on the `Link` component. When you want to scroll to something in a container you should give that container an `id` then on the `Link` component set the `containerId` as the same string.
I hope this helps I'm quite new to all of this :)

**Comment by corysimmons** [comment]
Ah yeah, thanks @SamWyld 

So you need to use

```
<Link to="xyz" containerId="abc">
  Go to XYZ within the #abc div
</Link>

<div id="abc">
  <Element name="xyz">XYZ</Element>
</div>
```

🙇

**Comment by corysimmons** [comment]
Hmm... the math on it is broken and it ends up offset incorrectly. Have to do a bunch of state juggling + refs + etc just to get `<Link>` to scroll to top of an element. 💢
