### ISSUE TITLE
How do I do infinite scrolling?

### ISSUE THREAD

**Issue by Ashwin117** [fisshy/react-scroll#333]
No docs on this...

**Comment by fisshy** [comment]
You can't.

**Comment by Ashwin117** [comment]
@fisshy I would like to see an explanation or a way to do this or some knowledge on where to look at to implement this....just replying with "You can't" and closing this issue off seems a bit insensitive.

**Comment by fisshy** [comment]
That's a much better question then your former one.

There's currently no way to solve this, this library solves Link to Element and has no infinite scroll support.

What you could do, is listen to the scrollevent on the element you are scrolling inside, and once you reach the bottom you add more items.

Take this example, the code wont compile, but you get the hang of it.

```
<div class="scroll-view" onScroll={this.scroll}>
    your content...
</div>

let element = this;
let isAtBottom = false;
let isStillAtBottom = false;

scroll = () => {
            isAtBottom =  element.scrollTop > (element.scrollHeight - element.offsetHeight  - this.offset);

            if(isAtBottom && isStillAtBottom) {
                return;
            }

            if(isAtBottom && !isStillAtBottom)
            {
                isStillAtBottom = true;
                addMoreItems();
            } else {
                isStillAtBottom = false;
            }
}

```
