### ISSUE TITLE
Move changelog to CHANGELOG.md

### ISSUE THREAD

**Issue by MartinCerny-awin** [fisshy/react-scroll#337]
It is de facto standard to have changelog inside CHANGELOG.md file or inside releases. It would be good to move it from README.md to one of these locations

See:
https://github.com/facebook/react/blob/master/CHANGELOG.md
https://github.com/reduxjs/redux/blob/master/CHANGELOG.md https://github.com/reduxjs/redux/releases

**Comment by MichaelDeBoey** [comment]
Closed by 186698e
