### ISSUE TITLE
Is there a way to get the value of selected Element onScroll?

### ISSUE THREAD

**Issue by wonjiky** [fisshy/react-scroll#354]
Hi,

I have a list and content on separate components, both populated from a same json file.
I can see retrieving the json object when of selected 'Element' or 'div' is possible through passing an onClick. But does anyone know how to retrieve the objects values when the user scrolls into an 'element'?

Thank you

**Comment by fisshy** [comment]
Hi,

You do have "onSetActive" on Link elements if that give you what you want.

**Comment by wonjiky** [comment]
Ah! I missed that part of the documentation. Thank you so much!

**Comment by fisshy** [comment]
Great! Did it solve your issue?
