### ISSUE TITLE
doesn't seem to be working with react 1.0.0

### ISSUE THREAD

**Issue by davis** [fisshy/react-scroll#36]
I'm using JSPM

```
import React from 'react';
import { Link as ScrollLink, Element } from 'react-scroll';

<ScrollLink to={this.props.target} smooth={true}>hi</ScrollLink>

<Element name="image"/>
```

when i run it says i have two version of React running
also the package requires react-dom!

**Comment by fisshy** [comment]
will look into it :)

**Comment by bdefore** [comment]
i'm running into this too, when was your last published npm version that did not use ReactDOM and 0.14?

**Comment by bdefore** [comment]
I'm not sure if this is related, but whenever if I add `<ScrollElement name="header" className="foo">asdf</ScrollElement>` to a render block in my React 0.13 project, I get the error `Unhandled promise rejection TypeError: Cannot read property 'firstChild' of undefined`

**Comment by fisshy** [comment]
Can you write a jsFiddle with your issue? And I'll try to solve it :)

**Comment by pdw207** [comment]
I am using React version 0.14.2 and was getting an error relating to ReactDOM. I made the following change to fix the node module on my local machine but not sure how to make this change backwards compatible. 
```
// react-scroll/lib/mixins/Helpers:107`
var domNode = ReactDOM.findDOMNode(this);
````
to 
```
// react-scroll/lib/mixins/Helpers:107`
var domNode = React.findDOMNode(this);
````

**Comment by fisshy** [comment]
updated to work with latest react. Use older version of react-scroll if needed to work without ReactDOM
