### ISSUE TITLE
scrollTo element name does not scroll exactly to element

### ISSUE THREAD

**Issue by monkeydri** [fisshy/react-scroll#361]
`document.getElementById(id).scrollIntoView();` works perfectly but `scroller.scrollTo(id, { containerId: 'container' })` scrolls slightly above and I cannot correct it with offset because the mismatch is not fixed (ie. difference between correct position and scrolledPosition varies).

my `Element`s are `.map()`ped like with following `render()` : `<Element name={doc._id} id={doc._id}>content</Element>`.

**Comment by nvma** [comment]
Same problem.

**Comment by tharakabimal** [comment]
Yes, I have the same problem.

**Comment by fisshy** [comment]
Feel free to make a PR, I Haven't had the time to fix this yet.

**Comment by nvma** [comment]
Well, maybe it will also help someone,
I've spent some time going through this issue on my end and I've realized that the problem in my case was in the structure of layout.

I have a grid of products with images and text divided by categories, each category is wrapped in `Element`. The grid is fairly large so I lazily load actual images substituting them with placeholders off screen. And some of those real images differ in height, by only a 10-20px, but that's enough to offset the layout upon scrolling.

So as far as I understand, when the grid loads it eagerly registers elements in the grid that uses placeholders and when the scroll is initiated placeholders start to get replaced via lazy load mechanism which makes the grid larger on Y-axis and it results in the scroll stopping just some 10-20 pixels above actual element.

I've verified that enforcing height consistency does solve this issue for me.

**Comment by Fi1osof** [comment]
My mistake: got sample with offset={50} from readme)))

**Comment by TeG2405** [comment]
https://github.com/fisshy/react-scroll/pull/368

**Comment by maracuja-juice** [comment]
Had this issue aswell in the current version.
Thanks to the code in the linked PR I figured out that I needed to set `position: relative` on the container.
