### ISSUE TITLE
React.StrictMode warning when using react-scroll

### ISSUE THREAD

**Issue by pelotom** [fisshy/react-scroll#362]
When using `<Scroll.Element />` inside of [`<React.StrictMode />`](https://reactjs.org/docs/strict-mode.html) (in React 16.6), the following warning is logged:

```
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: Element
```

**Comment by FredyC** [comment]
I am wondering if there are some alternative libraries that would be actually maintained :)

**Comment by FredyC** [comment]
@fisshy Can you please comment if you are actually planning on updating lib toward the future? Possibly rewrite to hooks to generally cleanup code base if you like.

**Comment by fisshy** [comment]
@FredyC I'm more then happy to recieve some PR's. But currently not planing any rewrite for Hooks. Might contribute if someone helps me.

**Comment by pelotom** [comment]
As the error message indicates, it's not necessary to update to hooks in order to fix this.

**Comment by FredyC** [comment]
@pelotom I haven't said rewrite is necessary, but it might be a good opportunity to simplify a codebase. Fix alone should be fairly simple for sure. Currently, it's not that painful problem yet to be concerned by it, but I expect by the end of the year it might become relevant.

**Comment by pelotom** [comment]
> I haven't said rewrite is necessary, but it might be a good opportunity to simplify a codebase.

Sure, but who's going to do this?
