### ISSUE TITLE
Is there a reason why react-dom is used?

### ISSUE THREAD

**Issue by alex-neurotrack** [fisshy/react-scroll#37]
Line 107 of `modules/mixins/Helpers.js` is the only place `ReactDOM` is used, and from a very small test, it seems as though `React.findDomNode` works in place of `ReactDOM.findDomNode`. I am new to React, is there a reason why the `react-dom` package is used?

**Comment by fisshy** [comment]
yes, v0.14 excluded some functions from it's core into multiple modules.
