### ISSUE TITLE
Scrollable div - always scrolls to top.

### ISSUE THREAD

**Issue by rmincling** [fisshy/react-scroll#375]
I have a container div which is scrollable and has css position set to 'relative'. For some reason no matter what element name i set it to scroll to, it always scrolls to the top of the parent div.

`scroller.scrollTo('chat-message-453', {
    duration: 1000,
    delay: 1000,
    smooth: true,
    containerId: 'participant-message-list'
});`

In this case the Element/div with name and id attributes set to 'chat-message-453' is near the bottom of the scrollable div.

Any advice/help would be much appreciated!

Cheers,

Rob

**Comment by fisshy** [comment]
Is the container scrollable? 

This code seems to work. Is yours similar ( except that you are calling the API directly ) 
```
 <Link activeClass="active" to="firstInsideContainer" spy={true} smooth={true} duration={250} containerId="containerElement" style={{ display: 'inline-block', margin: '20px' }}>
          Go to first element inside container
        </Link>

        <Link activeClass="active" to="secondInsideContainer" spy={true} smooth={true} duration={250} containerId="containerElement" style={{ display: 'inline-block', margin: '20px' }}>
          Go to second element inside container
        </Link>
        <Element name="test7" className="element" id="containerElement" style={{
          position: 'relative',
          height: '200px',
          overflow: 'scroll',
          marginBottom: '100px'
        }}>
          test 7 (duration and container)

          <Element name="firstInsideContainer" style={{
            marginBottom: '200px'
          }}>
            first element inside container
          </Element>

          <Element name="secondInsideContainer" style={{
            marginBottom: '200px'
          }}>
            second element inside container
          </Element>
        </Element>
```

**Comment by rmincling** [comment]
Fixed it. I didn't realise the parent container id I had set was not the direct parent, but a further level up. When i changed this to be the direct parent it worked fine.
