### ISSUE TITLE
onSetActive callback is being trigged multiple times as page scrolls to target anchor

### ISSUE THREAD

**Issue by brightpixels** [fisshy/react-scroll#383]
Hello,
I am trying to trigger a Google Analytics "pageview" when user scrolls to a new section. I am doing this via the onSetActive callback. However, if there is other sections/anchors between the current section and target section, the callback will be fired once for each section the page scrolls through. I am only interested in the target section in order to fire off a virtual pageview. Any suggestions to deal with this use case.

**Comment by fisshy** [comment]
Couldn't you create your own event and save the link they clicked on.

And filter out the triggered events with the one they clicked on. 

Currently the event is fired once you enter the component and onSetInactive is fired once you leave.

**Comment by fisshy** [comment]
Closed due to inactivity
