### ISSUE TITLE
Prop "to", when used with component properties, gives warning.

### ISSUE THREAD

**Issue by MaxiStarling56** [fisshy/react-scroll#386]
App.js:

    import Nav from './Nav';
    const App = () => {
      return (
        < Nav name="Name" id="#id" />
      );
    }

Nav.js:

    const Nav = ({ name, id }) => {
        return (
            <div className="nav">
                <ul className="menu">
                    <Link 
                         activeClass="active"
                         to={id}
                         spy={true}
                         smooth={true}
                         offset={0}
                         duration={500}
                         >{name}</Link>
               </ul>
            </div>
        );
    }

error:

    Warning: Failed prop type: The prop `to` is marked as required in `Link`, but its value is 'undefined'.
        in Link (at Nav.js: Number )

**Comment by MaxiStarling56** [comment]
sorry for the first code but it seems to not work

**Comment by fisshy** [comment]
Not sure why this occur for you. I just ran this code and it works for me.
```

<NavLink id="test1" >Test 1</NavLink>

const NavLink = ({id}) => {
  return <Link to={id} activeClass="active" className="test1" spy={true} smooth={true} duration={500} />
}
```
