### ISSUE TITLE
Smooth Scrolling isn't working

### ISSUE THREAD

**Issue by mikedevita** [fisshy/react-scroll#39]
Not sure whats up, probably something with my code.. when i click a Link element it just hops right to that element and doesnt do smooth scrolling...

anyone have any ideas?

**Comment by mikedevita** [comment]
nevermind! derpa derp..

it would help to specify a duration... `<li><Link to="home" spy smooth duration="500">Home</Link></li>`

**Comment by fisshy** [comment]
haha, glad you solved it by yourself!
