### ISSUE TITLE
Cannot read property 'isEqualNode' of null

### ISSUE THREAD

**Issue by zahorovskyi** [fisshy/react-scroll#405]
Hi @fisshy  !
I found an issue and I assume that it's related to these changes:
https://github.com/fisshy/react-scroll/commit/6c02a597e20a32310c5bdd38a6b7e32695950e40
@borunovm Could you check it, please?

![image](https://user-images.githubusercontent.com/7338339/71418236-2bbaa180-2672-11ea-9969-a4f54ee76a9a.png)

**Comment by borunovm** [comment]
Hello!
Thank you for the review and found the issue. I will check it tomorrow.

**Comment by borunovm** [comment]
Hello!
Please send me a piece of code how do you use react-scroll?

**Comment by borunovm** [comment]
I checked in various cases. I couldn't get this issue.
Please, send me a piece of your code.
I will try to fix it.

**Comment by mkantz84** [comment]
same issue hetre. 
version: 1.7.13 and 1.7.15

this is how i use it:
```
scroller.scrollTo('scrollHere', {
   duration: 300,
   smooth: true,
   containerId: `priorityElementID_${configurationId}`
 })
...
...
<Element name="scrollHere"></Element>
```

**Comment by borunovm** [comment]
It is should work. I created the same code and checked it. It works for me.
I am sorry.

You should verify the existence of the container.

**Comment by mkantz84** [comment]
the container exists.
when i changed the method `calculatingOffsetParent` in `utils.js` to:
```
var calculatingOffsetParent = function calculatingOffsetParent(c, t) {
  return t && t.offsetParent && t.offsetParent.isEqualNode(c) ? t.offsetTop : t ? t.offsetTop + calculatingOffsetParent(c, t.offsetParent) : null;
};
```
the problem fixed.
I dont know the consequences for the change, but maybe it could help you by finding the problem..
Note - on version 1.7.13, everything was OK. suddenly, after new installation (same version) it broke.
I tried downgrading to 1.7.12, but it still happens.

**Comment by borunovm** [comment]
Thank you for help. I know how I can fix this method. But I don't know how can I get this issue.

I don't know why you are getting this issue and what caused it.

I will test this method tomorrow and add additional checks

**Comment by borunovm** [comment]
I improved the condition and hope that this solves the issue.

**Comment by karthikvrao** [comment]
> Thank you for help. I know how I can fix this method. But I don't know how can I get this issue.
> 
> I don't know why you are getting this issue and what caused it.
> 
> I will test this method tomorrow and add additional checks

I am facing the same issue on the latest version 1.7.15.
@borunovm please see if this codesandbox [example](https://codesandbox.io/s/scroll-basic-llq0u) is helpful. 

It is the basic example from the repo in which I have just commented out most of the code not related to scrolling inside container. With default v1.7.7 it works but if you update to latest version it doesn't. 

You may setup the same code locally to the see the error in console.

**Comment by karthikvrao** [comment]
I also noticed that though the 'scrollTo' action itself works from v1.7.8 to v1.7.14, the offset (position where it scrolls to) is not correct as it overshoots.

**Comment by mstykow** [comment]
> I improved the condition and hope that this solves the issue.

It did not.

**Comment by LockhartJasonA** [comment]
I just wanted to add a comment that I am experiencing this issue as well as of 1.7.15, reverting to 1.7.14 fixes my code.

I am using the Link component // wrapper to navigate to the Element component wrapper.

utils.js:30 Uncaught TypeError: Cannot read property 'isEqualNode' of null
    at e (utils.js:30)
    at Object.scrollOffset (utils.js:34)
    at Object.scrollTo (scroller.js:86)
    at scrollTo (scroll-link.js:211)
    at handleClick (scroll-link.js:232)
    at Object.<anonymous> (react-dom.production.min.js:80)
    at _ (react-dom.production.min.js:100)
    at react-dom.production.min.js:104
    at E (react-dom.production.min.js:124)
    at N (react-dom.production.min.js:152)

**Comment by fisshy** [comment]
I believe I've solved the issue here.

https://github.com/fisshy/react-scroll/tree/pre-1.7.15

Checkout this branch, and I will merge it later.

**Comment by borunovm** [comment]
I don't see the changes

**Comment by fisshy** [comment]
Now, it helps to actually push them ;D

**Comment by gino8080** [comment]
seems broken with latest react ^16.12.0

**Comment by Benji-Leboe** [comment]
Hey guys, so after struggling with this issue all day, I think I've found the solution.

I'm not sure what changed, but the .offsetParent looks for the nearest *non-static* ancestor. That means that if your scroll container or the parent element that contains your <Element /> doesn't have an explicitly set position, the `calculatingOffsetParent` function recurses until it hits the body (which of course has an .offsetParent of `null`)

For a stopgap solution set the position of your container element and the parent of your <Element /> explicitly to something other than static.

I'm not sure what changed or why it worked before, but I got it working again after going nearly insane trying to solve this

**Comment by cursedcoder** [comment]
reverting to the old version does the trick

**Comment by fisshy** [comment]
Try the new version

**Comment by Reggino** [comment]
The new version fixes it!

**Comment by deltek-rossjackson** [comment]
It also fixed our issue. thank you.
