### ISSUE TITLE
I would like to say "thank you!". That "ignoreCancelEvents" made my day!

### ISSUE THREAD

**Issue by brvnonascimento** [fisshy/react-scroll#408]
I spent days researching on this particular issue. I'm using Intersection Observer to auto-scroll to the center of my div and create an "AirPods Pro-ish" style landing page. However, every Chromium browser would just trigger the event once, and for some reason (might be something with Next.js) if the user refreshes the page, it would never trigger again. I don't even know if this is the right place to do so, but thank you! For every one having issue with {scroll: 'smooth'} or { scroll-behaviour: smooth}, set ignoreCancelEvents to true.

**Comment by fisshy** [comment]
I'm glad it solved your issue! :)
