### ISSUE TITLE
react should be in "dependencies" not "devDependencies" in package.json

### ISSUE THREAD

**Issue by sethomas** [fisshy/react-scroll#412]
For lines like this: https://github.com/fisshy/react-scroll/blob/master/modules/components/Link.js#L3

React is required at run time, can you move "react" from devDependencies to dependencies in package.json?

**Comment by fisshy** [comment]
Make a PR! :)

**Comment by sethomas** [comment]
@fisshy https://github.com/fisshy/react-scroll/pull/414 thanks for response!
