### ISSUE TITLE
Understand the spy attribute and get scroll top.

### ISSUE THREAD

**Issue by hydrotik** [fisshy/react-scroll#43]
Would you be so kind to explain the spy attribute and also is there a way to get the scrollTop value?

**Comment by fisshy** [comment]
When a link and an element is linked together with "to" and "name" and spy is set to true, there will be a listener on the scrolling event notifying the link when it's scrolling over that element to make sure it gets highlighted. 

There's no scroll top now - maybe this is a good feature to have actually. Might rewrite some of the "scrollTo" logic to make sure it doesn't depend on elements or if someone else feels like doing it :)

**Comment by hydrotik** [comment]
Great thanks for the info. So is there an event I can  listen to within the element that I could use to trigger an animation. For example click the link.. scroll to the element. When the scroll is complete then an event fires that I can use to trigger another event? Hopefully I am understanding you correctly:)

I can take a look at the code and see if I can make some time for a PR.

**Comment by hydrotik** [comment]
Also if I understood you correctly above, if you could share an example of hooking into that event, would be greatly appreciated!

**Comment by fisshy** [comment]
Theres no callbacks at the moment - that's a good feature to have as well actually.
I might do some changes in the upcoming days if nobody else feels motivated to send a PR :)

**Comment by hydrotik** [comment]
That would be awesome, I tried to add a window scroll listener and pushed that info into the props and it was non performant visually. If there are callbacks then I can use the scroll event to trigger the animation. There might be a better performing way to handle it, but I haven't figured or come across it yet:)

Should I open another issue request for callbacks?

**Comment by fisshy** [comment]
Yeah do that, this is possibly something I can solve tonight ;)

**Comment by hydrotik** [comment]
Ok Will do!

**Comment by OhCoder** [comment]
hey! this problem already have done yet?
