### ISSUE TITLE
Scroll event callbacks and possibly expose scrollTop

### ISSUE THREAD

**Issue by hydrotik** [fisshy/react-scroll#44]
Hopefully detect scroll animation complete, but start and interrupt would be helpful as well.

Cheers!

**Comment by fisshy** [comment]
Most likely to solve this tomorrow - got some time off :)

**Comment by hydrotik** [comment]
:beers:

**Comment by fisshy** [comment]
Hi, I've fixed the begin/end events of scrolling/animation

My suggestion is to include it as a mixin ( see Usage on how to do it )
Or checkout the API here.
https://github.com/fisshy/react-scroll#scroll-events
