### ISSUE TITLE
Keep active class until next is reached

### ISSUE THREAD

**Issue by zoltanseer** [fisshy/react-scroll#458]
How can I keep the active class until the next section is reached, even if the "active" section is over? 
For example, the navigation has 2 items:
- Section 1
- Section 2

Content: 
<table>
<tr>
	<td>Section 1
<tr>
	<td> Section X
<tr>
	<td> Section 2
</table>

I would like to have the Section 1 active also when scrolling over Section X

**Comment by fisshy** [comment]
You could listen to the events onactive/inactive and handle the logic yourself. 

Our spy does not support this feature.
