### ISSUE TITLE
Scrolling Stuck Issue in Chrome

### ISSUE THREAD

**Issue by yushanwebdev** [fisshy/react-scroll#463]
I implemented “react-scroll” to this site. (Check the highlighted area in the screenshot)
[URL](https://www.lymited.com/buy/nike-air-max-1-paris-bespoke-2017)

![site](https://user-images.githubusercontent.com/25406148/118233649-d0c85b00-b4af-11eb-911c-1fcaefcb719a.png)

In Chrome when you click on that down-arrow, the page scrolls a little bit down & stick for a few seconds & then start to scroll again to the section.

Here implementation is done by using [Link](https://github.com/fisshy/react-scroll#propsoptions)

Could somebody provide a solution for this chrome related issue? Any suggestion is highly appreciable.

**Comment by fisshy** [comment]
I can't even see that down button, using chrome on windows.

But I did a quick performance check using dev tools in chrome, and by pressing "Talk to an expert" which then triggers a scroll to the contact form. The animation then drops to 3-5 fps for a short period of time which makes the scrolling flicker. 

Could it be that you animate some other stuff while you are scrolling? (header etc)

Try to exclude all animation and see if the scrolling still "pauses" for you, if that be the case, try use requestAnimation frame for animations

**Comment by yushanwebdev** [comment]
Thank you very much @fisshy

**Comment by fisshy** [comment]
Glad I could help! :)

**Comment by roydenrego** [comment]
@yushanwebdev Could you detail on what was causing the issue on your site? I have been facing the same problem in two of the new sites I'm currently working on. 

Based on @fisshy's answer, I can confirm that there are no other animations that have been coded into the site.

**Comment by yushanwebdev** [comment]
@roydenrego FPS rates can drop because of many reasons. 

I always update a value inside the page scrolling function. It caused the page’s react-scroll animation to stick for a few seconds. 

Yours also might have a thing like that. It can be something other than animations. Use **Performance Tools** in the browser to find out that.
