### ISSUE TITLE
Trigger click Event

### ISSUE THREAD

**Issue by MarkusHeinisch** [fisshy/react-scroll#467]
How can i trigger your link-component? This works with normal html-elements, but not with your component (has to remove the first "<" and last ">" because github creates trash):

Link ref={ref} to={to} smooth={true} duration={500} onClick={onClick}>{text}</Link
div onClick={() => clickMyLink(ref)}>FOO</div
const clickElement = (ref) => { ref.current.click(); };

**Comment by fisshy** [comment]
I'm pretty sure somehow this should work, could you provide a codesandbox for this?

PS: You could always wrap your code in "``" and the "<>" will not disappear.

**Comment by MarkusHeinisch** [comment]
https://codesandbox.io/s/fdbj4s33na2-v3exi

**Comment by MarkusHeinisch** [comment]
@fisshy Hey did you find some solution? I'cant solve this problem. :-(

**Comment by fisshy** [comment]
Yes, you could do it like this.

https://codesandbox.io/s/exciting-morning-xnc67?file=/src/App.js

**Comment by MarkusHeinisch** [comment]
Thank you sir. You solved my problem.

**Comment by fisshy** [comment]
Glad I could help! :)
