### ISSUE TITLE
Smooth Scroll does not work with Bootstrap 5

### ISSUE THREAD

**Issue by roydenrego** [fisshy/react-scroll#475]
When using the Bootstrap 5 CSS from the official bootstrap npm package, the smooth scroll lags for a bit and then start scrolling to the target div.

CodeSandbox replicating this issue: https://codesandbox.io/s/mystifying-bash-zenh8

**Comment by fisshy** [comment]
It doesn't lag for me, I get the same effect with our without bootstrap.

What browser?

**Comment by roydenrego** [comment]
@fisshy I faced this issue on Chrome, Chrome for Android and Chromium Edge. I haven't really tested thoroughly on other browsers. 

Below are some video examples below in case it helps. Focus on the "Red" text in the red box to notice the lag.

With Bootstrap: https://imgur.com/a/oBiUEQ8
Without Bootstrap: https://imgur.com/a/nOnEmHl

**Comment by keXXpert** [comment]
Have the same issue in Chrome. Firefox and Safari work fine.

**Comment by roydenrego** [comment]
@keXXpert Hey thanks, this worked and .

Could you explain how this CSS solves the issue with Bootstrap 5?

> Have the same issue in Chrome. Firefox and Safari work fine. Btw, I'm using it with Next.js 11
> 
> This seems to solve the issue:
> `:root { scroll-behavior: auto !important; }`

**Comment by keXXpert** [comment]
@roydenrego I'm not quite sure myself. I thought Bootstrap might interfere with this CSS value. So I downloaded Bootstrap CSS file, found this key set to 'smooth', and redefined this to default 'auto' in my own CSS.

I was going to use this 'smooth' feature in the first place, but it doesn't work with Safari, so I end up using 'react-scroll' and resetting this to default :)

**Comment by roydenrego** [comment]
> @roydenrego I'm not quite sure myself. I thought Bootstrap might interfere with this CSS value. So I downloaded Bootstrap CSS file, found this key set to 'smooth', and redefined this to default 'auto' in my own CSS.

@keXXpert Haha, that about sums up the life of a developer.

@fisshy Should we close this issue since there is a solution now or should we keep it open so that we work on a fix to support Bootstrap 5?

**Comment by fisshy** [comment]
@roydenrego I guess we could close it, since there's a workaround.
