### ISSUE TITLE
Convert mixins to HOCs

### ISSUE THREAD

**Issue by neverfox** [fisshy/react-scroll#48]
As I'm sure you know, mixins are dead; long live HOCs. Any plans to refactor?

**Comment by fisshy** [comment]
yes I know - should look into it unless anyone feels like contributing :)

**Comment by fisshy** [comment]
I might rewrite it on wednesday :)

**Comment by fisshy** [comment]
https://github.com/fisshy/react-scroll/commit/b085225cb527c80a96d0922f3c848a5c2ae1c611

As of version v0.36.0 react-scroll no longer supports mixins.
