### ISSUE TITLE
Divs with dynamic heights

### ISSUE THREAD

**Issue by kuiro5** [fisshy/react-scroll#49]
Awesome library, using it on my personal portfolio website, www.kuiros.io. I have divs/sections that are dynamic in height so that they change height when I resize the window. This messes up the anchors where the links scroll to. Is there any way to refresh the anchor positions on a window resize? Thanks a lot.

**Comment by fisshy** [comment]
Not sure, but it should be possible to do it. I'm surprised it's not dynamic already. I can look into it.

**Comment by kuiro5** [comment]
Thanks, I appreciate it.

**Comment by kuiro5** [comment]
I was wondering if you had any time to look into the dynamic height issue? Really appreciate your help.

**Comment by fisshy** [comment]
I'm sorry haven't gotten the time to do it yet - I'm going to sit down and rewrite some of the parts to fit future react this week probably and I will fit this case in there as well.

**Comment by idw111** [comment]
I have the same issue.
I set the div height 100vh
Resizing the browser window result in wrong anchor highlight

**Comment by oizie** [comment]
It happens to accordions too.
