### ISSUE TITLE
SEO problem (Link not crawlable)

### ISSUE THREAD

**Issue by chinhoe** [fisshy/react-scroll#495]
First of all, thanks for the helpful library.

Just want to ask here to see if this happens to anyone else too. I had a website that uses react-scroll's `Link` and `Element`. Few months ago, the SEO was still 100 until recently when I did another lighthouse test, and the SEO dropped to 90 saying that the links are not crawlable.

Just wondering if there is something that I can do on my side to fix this?

![image](https://user-images.githubusercontent.com/15047293/153734481-4f2cc331-0ce1-4a87-bc08-5c2e945abbbd.png)

**Comment by fisshy** [comment]
Have you tried adding the href tag?

**Comment by chinhoe** [comment]
Do you mean passing another href prop to react-scroll's `Link`? Currently what I have is a shared component using `Link` which I created by referring to the usage in the docs.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/15047293/154428677-8ddcbf28-a0bb-440e-8723-d0e5c520864e.png">

**Comment by DaniSido** [comment]
Hi everyone,
may I know what you have put inside the href? because if I put '#' the plugin no longer works, while if I leave it empty the error in the SEO persists ....
thank you

**Comment by chinhoe** [comment]
> Hi everyone, may I know what you have put inside the href? because if I put '#' the plugin no longer works, while if I leave it empty the error in the SEO persists .... thank you

For my case, its just a single page website, so I just put '/' in the `href`. Not sure if that helps.
