### ISSUE TITLE
dead code published (`build/npm/modules`)

### ISSUE THREAD

**Issue by kewde** [fisshy/react-scroll#496]
I noticed that the folder `build/npm/modules`  contains the same code as in `/modules` and I don't see any way that `build/bpm/modules` is referenced. Could it be that this code is accidentally published in the package?

**Comment by kewde** [comment]
cc @fisshy

**Comment by fisshy** [comment]
@kewde yes, that's probably a mistake from my side, it should not be there.

**Comment by fisshy** [comment]
I've now removed the duplication, thank you for noticing :)
