### ISSUE TITLE
`unmount` should remove specific references of callbacks instead of clearing the stack

### ISSUE THREAD

**Issue by cheapsteak** [fisshy/react-scroll#50]
When using react router and ReactTransitionGroup, the `componentDidMount` of the incoming view gets called before the `componentWillUnmount` of the outgoing view is called. This results in the callbacks added by the new view being cleared when the old component leaves.
 

The Helpers.js mixin should keep references to the callbacks passed to scrollSpy, and pass those as arguments into `scrollSpy.unmount()`, and scrollSpy's unmount would need to accept those arguments and slice them out of the array instead of clearing the entire array.

https://github.com/fisshy/react-scroll/blob/master/modules/mixins/scroll-spy.js#L40-L41
```js
this.spyCallbacks = [];
this.spySetState = [];
```
the above should be turned into something like

```js
this.spyCallbacks.splice(this.spyCallbacks.indexOf(spyCallbackToRemove), 1);
this.spySetState.splice(this.spySetState.indexOf(spySetStateToRemove), 1);
```

**Comment by fisshy** [comment]
yes you're correct, make a PR and I will merge it. Or I might fix this when I get time to do it :)

**Comment by cheapsteak** [comment]
I do have a working implementation, but the code quality is rather poor as we're nearing deadline of a project and just needed something that worked asap

You can see what I have here:

https://github.com/Jam3/react-scroll/blob/master/modules/mixins/Helpers.js
https://github.com/Jam3/react-scroll/blob/master/modules/mixins/scroll-spy.js

Not very happy with the naming (basically added `__spy` in front of a bunch of previously closure-ed variables and stuck them onto `this`). Not the cleanest solution, I'm not really familiar enough yet with react to know what the cleanest solution would be. Open to guidance.

Thanks for the library btw, it's saved us quite some time.

**Comment by fisshy** [comment]
Glad It helped mate! I will adjust your code later tonight and make a PR to your branch and then merge into the project :)

**Comment by cheapsteak** [comment]
:)
