### ISSUE TITLE
iOS 15.4 breaks scrolling animation

### ISSUE THREAD

**Issue by firatciftci** [fisshy/react-scroll#502]
Hello,

I have just updated my iOS devices to iOS 15.4, which was released earlier today (March 14th, 2022) with changes to scrolling behavior in Safari. These changes have broken the scrolling animation that used to work perfectly fine before. Here is the code I have been using:

```js
scroller.scrollTo('inputElement', {
    smooth: true,
    offset: -5,
    delay: 0,
    duration: 500,
});
```

Here, ```inputElement``` is an ```<Element/>``` surrounding an ```<input/>```. The expected behavior is for the window to scroll to the top of the text input box whenever it is focused. The current behavior achieves this, but with a very significant stutter in the scrolling animation.

You can access the website through the following link for a live example: https://www.nisanyansozluk.com
The animation should trigger when you focus on the text input that reads "Türkçe sözcük ara..." (note that it is only functional on mobile devices).

**Comment by fisshy** [comment]
Hello,

Good finding, yes latest  iOS has broken a lot of stuff. 
Let me look into it and I'll see if it's an easy fix.

**Comment by firatciftci** [comment]
@fisshy Any updates on this? The problem still seems to be present.
