### ISSUE TITLE
Babel Error

### ISSUE THREAD

**Issue by ponty96** [fisshy/react-scroll#51]
Babel showing this error in /node_modules/react-scroll/lib/mixins/Helpers.js
<code>
Line 116: Unexpected token <
You may need an appropriate loader to handle this file type.
   className = this.props.className
  }
  return <Component {...this.props} {...this.state} className={className}  onClick={this.handleClick} />
 }
  });
</code>

**Comment by fisshy** [comment]
Will look into it tonight.

**Comment by ponty96** [comment]
please do man, thou I'm looking @ a possible fix. If I get one, I'll submit a PR

**Comment by fargerio** [comment]
Probably related:
babel gives me an error even earlier in the same file, somehow babel does not accept the ES6 Syntax in Helpers.js:
`node_modules/react-scroll/lib/mixins/Helpers.jsx:6
const { bool, object, string, func, number } = React.PropTypes;
      ^

SyntaxError: Unexpected token {`

**Comment by fisshy** [comment]
thanks, will look into it. Somthing came up yesterday, will try to solve it today.

**Comment by ponty96** [comment]
okay. @fisshy  any possible fix yet?

**Comment by wavymav** [comment]
I'm having the same problem

**Comment by fisshy** [comment]
Sorry for the delayed fix guys

fixed in  v1.0.1 on npm or https://github.com/fisshy/react-scroll/commit/2a492f56416c486c16a517dfdafe981158e9f096 for the code

**Comment by mmahalwy** [comment]
@fisshy having same problem too... even with 1.0.1

**Comment by fisshy** [comment]
Fixed thanks to @mmahalwy https://github.com/fisshy/react-scroll/commit/7ae01d4f9cffd7b86e60922f1d9e5be98a6c4a1c and v1.0.2 on npm
