### ISSUE TITLE
SCRIPT65535: Invalid calling object - animate-scroll.js (96,3)

### ISSUE THREAD

**Issue by HeyWrecker** [fisshy/react-scroll#55]
Hello! I started testing an implementation of react-scroll and everything seems to work great in Safari 9, Firefox 44.0.2, and Chrome 48.0.2564.109, all on MacOS X 10.10.5. I'm using VirtualBox with the IE11 - Win11.ova that's available from Microsoft to do some MSEdge testing. The error mentioned in the subject shows up in the console of Edge when I attempt to click on a link that was set-up with react-scroll.

The way my implementation is currently set-up is that I have a StickyHeader component that contains the event listeners and Link components for react-scroll and a separate component that contains the Element react-scroll component. A basic outline would look something like this:

`<Lesson>
<StickyHeader />
<Element>
inner content
</Element>
</Lesson>`

I wouldn't think that having the Link and Element components in two separate files would cause a problem and so far the only error I've seen has been in IE and not the three other major browsers. To test for this, I removed the StickyHeader component and added a vanilla Link component and still received the error.

Any insight or advice you might have would be greatly appreciated.

![virtualbox_ie11 - win10_19_02_2016_14_49_35](https://cloud.githubusercontent.com/assets/3180594/13187267/386c4b48-d718-11e5-99ae-c33356447036.png)

**Comment by HeyWrecker** [comment]
I think I found it. The reference to "requestAnimationFrame(animateTopScroll);" on lines 77 & 96 need to be replaced with "requestAnimationFrame.call(window, animateTopScroll);".

Doing this removes the error from MSEdge (IE 11) and react-scroll then functions as expected.

**Comment by fisshy** [comment]
Published in v1.0.3
