### ISSUE TITLE
It is not compatible with the latest Next.js.

### ISSUE THREAD

**Issue by KangXinzhi** [fisshy/react-scroll#555]
![image](https://github.com/fisshy/react-scroll/assets/50164727/2847bbe9-3a4f-4699-bd7d-3c247a2c5d49)

![image](https://github.com/fisshy/react-scroll/assets/50164727/bcb4aa31-af73-40b8-97d4-b0353c984b75)

**Comment by alvis** [comment]
Also confirm it doesn't work with `next@13.4.4` and `react-scroll@1.8.9`. Same error related to an undefined super expression. :(

**Comment by datvnn** [comment]
I got the same error, it disappeared after installing `smoothscroll-polyfill`.
`"next": "^13.4.1", "react-scroll": "^1.8.9", "smoothscroll-polyfill": "^0.4.4",`

**Comment by KangXinzhi** [comment]
> I got the same error, it disappeared after installing `smoothscroll-polyfill`. `"next": "^13.4.1", "react-scroll": "^1.8.9", "smoothscroll-polyfill": "^0.4.4",`

hi, I have tried to solve this problem by adding the following code at the top of the page where you use react-scroll```use client```,like this:
```
'use client'
import React from 'react'
import Link from 'next/link'
import { Link as ScrollLink } from 'react-scroll'

function App() {
  return (
    <div>
      xxx
    </div>
  )
}

export default App
```

**Comment by KangXinzhi** [comment]
> Also confirm it doesn't work with `next@13.4.4` and `react-scroll@1.8.9`. Same error related to an undefined super expression. :(

I have tried to solve this problem

**Comment by Ricka7x** [comment]
Same here, running `next@13.4.2` `react-scroll@1.8.9`

**Comment by morgnism** [comment]
Can confirm adding `'use client'` to the component using `react-scroll` will fix this issue.

**Comment by Ciscoo91** [comment]
I also confirm that adding 'use client' solved the problem 👍

**Comment by intuity-hans** [comment]
your solutions suggest that you are using the app router. is this also present when using the pages directory?

**Comment by Ciscoo91** [comment]
I haven't tried using the pages directory, but based on the Next.js documentation, pages in the app directory are server components by default, while pages in the pages folder are client components by default. Therefore, I believe you don't need to use 'use client' in the components when using the pages folder. You can find this information in the [Next.js documentation](https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration#step-4-migrating-pages).

Furthermore, the documentation also explains why some third-party packages need to be in client components. You can read more about it [here](https://nextjs.org/docs/getting-started/react-essentials#third-party-packages).

**Comment by xiaojiudev** [comment]
Is there any other similar library support for Nextjs13?

**Comment by leandroruel** [comment]
> Is there any other similar library support for Nextjs13?

as the previous replies said, all pages/components in Next 13 are by default server components, you have to set "use client" at the top of your component/page.

i also tried search by a different lib but no success =/

**Comment by samullman** [comment]
Geez this new next js causing everything to break lol
