### ISSUE TITLE
scrollSpy performs unnecessary work

### ISSUE THREAD

**Issue by sfrdmn** [fisshy/react-scroll#57]
Seems like the `mount` method in [scroll-spy.js](https://github.com/fisshy/react-scroll/blob/master/modules/mixins/scroll-spy.js#L6) is getting called every time a `<Link .../>` is mounted, resulting in multiple scroll listeners on `document`. Since scrollSpy is a global singleton which manages its own listeners, there should be a check which only adds the scroll listener if there is none already

I'll probably up a PR for this, unless I'm misreading the whole thing

**Comment by sfrdmn** [comment]
Oh, the same goes for `unmount`. The fix suggested in #50 would apply here as well

**Comment by fisshy** [comment]
Yes you're correct, feel free to make a PR :)
