### ISSUE TITLE
API to force a scroll?

### ISSUE THREAD

**Issue by HeyWrecker** [fisshy/react-scroll#61]
Is there a way to force a scroll to top without clicking on ScrollToElement / Link? For example, if I'm on a page with params and navigating between them, currently it keeps me at the page position rather than scrolling me back to the top of the page. I'd like to manually do this if it's possible.

**Comment by fisshy** [comment]
Yes there Is now. Exposing the scroll api now. Checkout the examples page https://github.com/fisshy/react-scroll/blob/master/examples/basic/app.js
