### ISSUE TITLE
API to scroll to <Element>

### ISSUE THREAD

**Issue by petermikitsh** [fisshy/react-scroll#63]
Is there a way to programmatically scroll to a named `Element`?

**Comment by fisshy** [comment]
hm good question, I don't think so to be honest. This is a good feature to have :)

**Comment by fisshy** [comment]
There's a new feature scroll.scrollTo that can take you to a current position on the site. Step two would be to be able to pass an element to it and not only an absolute position.

**Comment by snakeyak** [comment]
scroll.scrollTo doesn't seem to support 'delay' prop unfortunatelly

**Comment by fisshy** [comment]
check out the new version v1.0.11. Now you can pass all the available props as options as well. https://github.com/fisshy/react-scroll/commit/e9051d41a7ef0be4ab8cdd43f027c0a47a07014e

**Comment by snakeyak** [comment]
Great, thank you!

**Comment by GabrielCTroia** [comment]
@fisshy Shouldn't this issue be closed now that it's implemented?

**Comment by fisshy** [comment]
@GabrielCTroia you are correct, it does work with scroller. check out the readme enhanced by @GabrielCTroia
