### ISSUE TITLE
Changelog for ~1.0?

### ISSUE THREAD

**Issue by emilecantin** [fisshy/react-scroll#67]
I'm currently using react-scroll@0.35.0; I'd like to know if I can safely upgrade to 1.0.x. Is is possible to write a quick changelog listing the breaking changes between 0.x and 1.x?

Thanks!

**Comment by fisshy** [comment]
No big changes to be honest, I've kept the same "standard code" and it still works. 

I'm pretty sure it would "just work"  for you.

**Comment by emilecantin** [comment]
Okay, thanks! I thought there were some breaking changes because of the major version jump, but I guess you just felt it was stable enough for a 1.0?

**Comment by fisshy** [comment]
Yes exactly and a more convenient version
