### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by smashercosmo** [fisshy/react-scroll#72]
Duplicated code was committed in 951f21b1df82a45bcca7eaa023f10aa4ea4b35d9. You can see it [here](https://github.com/fisshy/react-scroll/blob/951f21b1df82a45bcca7eaa023f10aa4ea4b35d9/modules/mixins/Helpers.js#L24-L50). This is a bug itself, but the worst thing is that it causes Safari 8 to throw js error.

**Comment by fisshy** [comment]
Sorry about that, Must have been tired yesterday :) 
solved here - https://github.com/fisshy/react-scroll/commit/ee10f6f20037758de6086464a7604b7644f95b37

**Comment by smashercosmo** [comment]
Thx for quick response)
