### ISSUE TITLE
Dependencies not being installed via npm

### ISSUE THREAD

**Issue by TedAvery** [fisshy/react-scroll#74]
I'm trying to integrate this package with npm, but your dependencies aren't being installed through `npm install`. I notice this based on the logs, but here's an example error I get from webpack.

```
ERROR in ./~/react-scroll/lib/mixins/animate-scroll.js
Module not found: Error: Cannot resolve module 'object-assign' in /js/directory/node_modules/react-scroll/lib/mixins
 @ ./~/react-scroll/lib/mixins/animate-scroll.js 3:13-37
```

I notice there are no dependencies in the [package.json](https://github.com/fisshy/react-scroll/blob/master/build/npm/package.json) in the build/npm folder either.

**Comment by fisshy** [comment]
Must have missed them. https://github.com/fisshy/react-scroll/commit/8ef3fde2a8b6db7998d719f0c537319a1943462e should solve it
