### ISSUE TITLE
Move to react 15?

### ISSUE THREAD

**Issue by elisherer** [fisshy/react-scroll#75]
Can someone update it to support react 15? currently it adds a whole react 0.14 into my bundle to support this feature.

**Comment by AlexDultsev** [comment]
First of all thank you for that awesome package! 
I have to admit that with React 15 we also get these console messages:

`Warning: Element: 'ref' is not a prop. Trying to access it will result in 'undefined' being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)`

`Warning: Element: 'key' is not a prop. Trying to access it will result in 'undefined' being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://fb.me/react-special-props)`

`Uncaught Invariant Violation: traverseParentPath(...): Cannot traverse from and to the same ID, ''`

**Comment by fisshy** [comment]
Gonna solve this tonight. Expect a new version in 1-2 hours... and will solve the errors as well.

**Comment by fisshy** [comment]
Solved now. The errors is not in the react lib. Can't reproduce the warnings. I get no warnings using react-scroll with react v15.
