### ISSUE TITLE
Duplicate "react-addons-test-utils" in "package.json" (node "devDependencies"). npm install failed

### ISSUE THREAD

**Issue by vadimgubin** [fisshy/react-scroll#76]

**Comment by vadimgubin** [comment]
from npm-debug.log


_199 verbose validateInstall loading /home/vadim/Sources/Libraries/react-scroll/package.json for validation
200 verbose stack Error: The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
200 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:125:32
200 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:268:7
200 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
200 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
200 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
200 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
200 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
200 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
200 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
200 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
201 verbose cwd /home/vadim/Sources/Libraries/react-scroll
202 error Linux 3.13.0-85-generic
203 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
204 error node v4.4.3
205 error npm  v2.15.1
206 error code EPEERINVALID
207 error peerinvalid The package react@15.0.1 does not satisfy its siblings' peerDependencies requirements!
207 error peerinvalid Peer react-dom@15.0.1 wants react@^15.0.1
207 error peerinvalid Peer react-addons-test-utils@0.14.8 wants react@^0.14.8
208 verbose exit [ 1, true ]_

**Comment by fisshy** [comment]
ah.. thanks for that!

Solved here https://github.com/fisshy/react-scroll/commit/882707703e062ea5c2ecff5c23bd42c244fe1a40
