### ISSUE TITLE
"object-assign," its dependency package, doesn't seem to be installed automatically.

### ISSUE THREAD

**Issue by crdelapazz** [fisshy/react-scroll#77]
When Browserify was bundling, I got this error:

`Error: Cannot find module 'object-assign' from 'C:\xampp\htdocs\portfolio\node_modules\react-scroll\lib\mixins`

But I fixed it simply by installing `object-assign`.

**Comment by fisshy** [comment]
hmm. I'm pretty sure it's included in dependencies? I will look into it.

**Comment by crdelapazz** [comment]
Thank you. I just checked if my `react-scroll` package was just outdated when I got that error, but it wasn't.

**Comment by fisshy** [comment]
Fixed now - I had put object-assign as perDependency. It's now fixed.
https://github.com/fisshy/react-scroll/commit/59439fb77f14727916d3474f43c3bd75b8d7478f
