### ISSUE TITLE
Scroll to Element

### ISSUE THREAD

**Issue by edgesoft** [fisshy/react-scroll#79]
Sorry for this question. Didn't see any other place to put this.
I'm trying the following but can not get a proper way to do it.

I have a large form with a lots of inputs. If the user clicks 'save' I want to be able to scroll to the first input that has the error. Tried to programmatically click the `Link` doesn't seem to work and I do not know the position of the input because the form is dynamic and can vary a lot from user to user.

**Comment by fisshy** [comment]
No problem! You can se and "id" on your input fields and use scrollTo and scroll to that Id

Or you can skip this lib and just focus that field.

something like this

var Scroll = require('react-scroll');
var scroller = Scroll.directScroller ;

<input id="firstName" />

// Somewhere else, even another file
scroller.scrollTo('firstName', {
  duration: 1500,
  delay: 100,
  smooth: true
})

**Comment by edgesoft** [comment]
Great @fisshy! That worked great.
