### ISSUE TITLE
webpack -wd in production

### ISSUE THREAD

**Issue by wowzaaa** [fisshy/react-scroll#87]
Hey

Any idea on why i am getting this in production env:

WARNING in scripts.min.js from UglifyJs
Condition always true [./~/scrollreveal/dist/scrollreveal.js:3,0]
Dropping unreachable code [./~/scrollreveal/dist/scrollreveal.js:5,3]

thanks,
Rares

**Comment by iDuuck** [comment]
Either the library was renamed in the last months, or you are posting something here for the wrong purpose, because it says `scrollreveal.js` and not `react-scroll.js` ...
