### ISSUE TITLE
server side rendering is failing

### ISSUE THREAD

**Issue by Ajar-Ajar** [fisshy/react-scroll#88]
Isomorphic / universal React web-apps are becoming the standard
When I use react-scroll and render on the server it throws the following error:

```
ReferenceError: window is not defined
        at startAnimateTopScroll (...\node_modules\react-scroll\lib\mixins\animate-scroll.js:113:3)
        at Object.scrollToTop (...\node_modules\react-scroll\lib\mixins\animate-scroll.js:138:3)
```

I'd suggest to wrap all dependencies to window with

```
var canUseDOM = !!(
  typeof window !== 'undefined' &&
  window.document &&
  window.document.createElement
)
if(canUseDOM ){
     // use window dependency...
}else{
  //have an alternative that wouldn't break functionality...
}
```

**Comment by fisshy** [comment]
you are right, feel free to make a PR if you want. Otherwise I can try fix it later :)

**Comment by vernondegoede** [comment]
@fisshy I created a PR which adds SSR support to react-scroll. https://github.com/fisshy/react-scroll/pull/209
