### ISSUE TITLE
Easing support

### ISSUE THREAD

**Issue by ryanmclaughlin** [fisshy/react-scroll#90]
Easing would be great to have as an option.

**Comment by ChazUK** [comment]
+1

**Comment by sugarshin** [comment]
+1

**Comment by cemarguvanli** [comment]
+1

**Comment by haniotis** [comment]
+1

**Comment by aspiers** [comment]
In case I'm not the only one who misinterpreted this being closed without explanation as a rejection of the feature request, this was added in 1.4.8.  Just search for "easing" in the README.md :-)
