### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by jmeas** [fisshy/react-scroll#91]
It'd be great to see a changelog for the different versions :v:

**Comment by fisshy** [comment]
You are right. Currently only updating the Readme. But there have been no breaking changes lately. 
But a changelog would be nice.

**Comment by fisshy** [comment]
Added a changelog in the readme now. I will try to update it for every new version that's published

**Comment by jmeas** [comment]
> But there have been no breaking changes lately.

React 14 => 15 in a bug fix release was a bit of a biggie.
