### ISSUE TITLE
Release process suggestions

### ISSUE THREAD

**Issue by jmeas** [fisshy/react-scroll#92]
The releases in this app aren't particularly easy to find. I think this is because of 2 reasons:
1. there aren't always dedicated release commits
2. the tags aren't always being maintained

I'm on an app that isn't upgraded to React 15 yet, so I was trying to find older releases. It'd be awesome if you started doing those 2 things – it'd make it way easier for consumers of this lib!

**Comment by fisshy** [comment]
You are correct, I will try to fix this today.
