### ISSUE TITLE
Unknown prop `smooth`

### ISSUE THREAD

**Issue by iDuuck** [fisshy/react-scroll#99]
There is something happening with the `<Link />` tag for me. What is this causing? Without the smooth attribute, the scroll isn't happening .. well, smooth...

```
warning.js:44 Warning: Unknown prop `smooth` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by fisshy** [comment]
What version do you use? It's an option to use animated scrolling or just scrolling.

**Comment by iDuuck** [comment]
I assume this is happening, because you are inheriting *all* props that the `<Link />` component received into the `<a>` element and this is not a supported one for this.

**Comment by iDuuck** [comment]
You can have a look at this (I was using the simple `frontend-boilerplate` from @tj). So just check it out.

**Comment by fisshy** [comment]
No problem, just install the latest v1.0.20. I actually fucked up the last publish I did so I had to republish it. It should fix your problems :)
